features_used:
    - "fea_los"
    - "fea_txt_msg_credit_lending_companies_unique_senders_count_03m"
    - "fea_rech_tot_amt_avg_03m"
    - "fea_int_usage_non_zero_usage_days_03m"
    - "fea_voice_tot_uniq_out_calls_03m"
    - "fea_handset_count_05m"
    - "fea_rech_tot_trx_sum_03m"
    - "fea_rev_voice_tot_sum_03m"
    - "fea_int_app_usage_social_media_data_vol_03m"
    - "fea_voice_tot_dur_12_5_am_03m"
    - "fea_voice_tot_uniq_inc_calls_03m"
    - "fea_txt_msg_banks_unique_senders_count_03m"
    - "fea_txt_msg_credit_lending_companies_incoming_count_03m"
    - "fea_txt_msg_ecommerce_shopping_incoming_count_03m"
    - "fea_txt_msg_mobile_wallets_incoming_count_03m"
    - "fea_txt_msg_outgoing_count_03m"
    - "fea_txt_msg_voice_ratio_incoming_03m"
    - "fea_txt_msg_incoming_count_03m"
    - "fea_int_usage_weekend_kb_usage_03m"

categorical_features: []

weeks_train: 12
weeks_test: 4
weeks_gap: 0

classifier_params:
    name: "catboost"
    params:
        iterations: 500
        l2_leaf_reg: 100
        depth: 6
        rsm: 0.5
        learning_rate: 0.05
        loss_function: "Logloss"
        verbose: False

common_query: "fea_los.notnull()"
train_query: "flag_bad_61 in ['good', 'bad', 'indeterminate']"
test_query: "flag_bad_61 in ['good', 'bad', 'indeterminate']"

train_target_expression_map:
    0: "flag_bad_61 in ['good', 'indeterminate']"
    1: "flag_bad_61 == 'bad'"
test_target_expression_map:
    0: "flag_bad_61 in ['good', 'indeterminate']"
    1: "flag_bad_61 == 'bad'"

reliability_diagrams_num_bins: 20

# gini.adjustment_type can be
#       'raw_proba' (raw probability)
#       'woe' (use of woe of bins instead of raw probability)
#       'avg_raw_proba' (use of average probability of bins instead of raw probability)
# gini.bin_type can be
#       'quantile'
#       'equal_size'
gini_params:
    adjustment_type: "raw_proba"
    bin_type: "quantile"
    num_bins: 20

extract_shap_values: True
log_train_data: True

# Do not modify parameters below, except for username at setup
use_spark: False

pai_tags:
    - "Kredivo"

weekstart_column_name: "weekstart"
