columns_to_include:
  msisdn: "msisdn"
  default_probability_score: "default_probability_score"
  refresh_date: "refresh_date"
  model_id: "model_id"

hdfs_base_path: hdfs:///data/landing/dmp_production/ # HDFS Base Path