pai_run: "d691a08b0efd49198e119c668bba558b" # stored in hdfs:///data/landing/gx_pnt/mck_dmp_ext/data_science/pai/test
score_column_name: "income_prediction"
predict_probability: False
post_processing: "exponential"
model_type: ""
binned: False
binned_score_column_name: ""
bin_thresholds: {}

hdfs_base_path: hdfs:///data/landing/dmp_staging/pilot/external/ # HDFS Base Path