repos:
  - repo: local
    hooks:
      - id: search-unwanted-strings
        name: Search Unwanted Strings
        description: Searching string that should not be commited
        entry: >
          kedro search-unwanted-strings
        language: system
        types: [ text ]
      - id: check-added-large-files
        name: Check for added large files
        description: Prevent giant files from being committed
        entry: check-added-large-files
        language: system
      - id: check-ast
        name: Check python ast
        description: Simply check whether the files parse as valid python.
        entry: check-ast
        language: system
        types: [ python ]
      - id: check-json
        name: Check JSON
        description: This hook checks json files for parseable syntax.
        entry: check-json
        language: system
        types: [ json ]
      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Check for files that contain merge conflict strings.
        entry: check-merge-conflict
        language: system
        types: [ text ]
      - id: check-yaml
        name: Check Yaml
        description: This hook checks yaml files for parseable syntax.
        entry: check-yaml
        language: system
        types: [ yaml ]
      - id: debug-statements
        name: Debug Statements (Python)
        description: Check for debugger imports and py37+ `breakpoint()` calls in python source.
        entry: debug-statement-hook
        language: system
        types: [ python ]
      - id: end-of-file-fixer
        name: Fix End of Files
        description: Ensures that a file is either empty, or ends with one newline.
        entry: end-of-file-fixer
        language: system
        types: [ text ]
        stages: [ commit, push, manual ]
      - id: mixed-line-ending
        name: Mixed line ending
        description: Replaces or checks mixed line ending
        entry: mixed-line-ending
        language: system
        types: [ text ]
        args: [ --fix=lf ]
      - id: no-commit-to-branch
        name: Avoid accidental commit to master, develop and release branch
        entry: no-commit-to-branch
        pass_filenames: false
        language: system
        args: [ '--branch', 'master', '--branch', 'develop', '--pattern', 'release-.*' ]
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: system
        types: [ text ]
        stages: [ commit, push, manual ]
      - id: bandit
        name: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        entry: bandit
        language: system
        types: [ python ]
        stages: [ commit, push, manual ]
        args:
          - -lll
          - -iii
          - -t
          - B101,B102,B103,B104,B105,B106,B107,B108,B110,B112,B201,B501,B502,B503,B504,B505,B506,B507,B601,B602,B603,B604,B605,B606,B607,B608,B609
        require_serial: true
      - id: kedro_lint
        name: kedro_lint
        entry: >
          kedro lint
        language: system
        types: [ python ]
