import os
os.chdir("/home/cdsw/project_dmp/")

! pip3 install scikit-learn==0.22.1
! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=concatenate_results_of_clustering_low
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow21




# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow96


# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow99
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low99
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow99