import os
os.chdir("/home/cdsw/project_dmp/")

# ## first run library
! pip3 install -r src/requirements.txt
! pip3 install -r src/requirements.txt
! pip3 install -r src/requirements.txt
! pip3 install -r src/requirements.txt
! kedro install

! kedro run --env=internal/ses --pipeline=ses_segmentation --node=rfm_step1
! kedro run --env=internal/ses --pipeline=ses_segmentation --node=rfm_step2
! kedro run --env=internal/ses --pipeline=ses_segmentation --node=rfm_step3
! kedro run --env=internal/ses --pipeline=ses_segmentation --node=rfm_step4
! kedro run --env=internal/ses --pipeline=ses_segmentation --node=rfm_step5
! kedro run --env=internal/ses --pipeline=ses_segmentation --node=rfm_step6
! kedro run --env=internal/ses --pipeline=ses_segmentation --node=rfm_step7
! kedro run --env=internal/ses --pipeline=ses_segmentation --node=selected_cols
! kedro run --env=internal/ses --pipeline=ses_segmentation --node=join_rfm_dmp_low
! kedro run --env=internal/ses --pipeline=ses_segmentation --node=join_rfm_dmp_medium
! kedro run --env=internal/ses --pipeline=ses_segmentation --node=join_rfm_dmp_high
! kedro run --env=internal/ses --pipeline=ses_segmentation --node=consistency
! kedro run --env=internal/ses --pipeline=ses_clustering --node=select_features_pandas_low
! kedro run --env=internal/ses --pipeline=ses_clustering --node=select_features_pandas_medium
! kedro run --env=internal/ses --pipeline=ses_clustering --node=select_features_pandas_high
! kedro run --env=internal/ses --pipeline=ses_clustering --node=Kmeans_Clustering_fit_low
! kedro run --env=internal/ses --pipeline=ses_clustering --node=Kmeans_Clustering_fit_medium
! kedro run --env=internal/ses --pipeline=ses_clustering --node=Kmeans_Clustering_fit_high






## Thirdh run training
# noted : before running this phase please changes the table on catalog.yml
#         1.) open catalog.yml
#         2.) find this 'dmp_master_table_all_partners' replaces with the latest updated by data engineer
#         3.) find this 'ses_low_num_cols_train' lets says 202010 to 202011
#         4.) find this 'ses_medium_num_cols_train' lets says 202010 to 202011
#         5.) find this 'ses_high_num_cols_train' lets says 202010 to 202011
#         6.) find this 'kmeans_low_train' lets says 202010 to 202011
#         7.) find this 'kmeans_medium_train' lets says 202010 to 202011
#         8.) find this 'kmeans_high_train' lets says 202010 to 202011
# noted : before running this phase please changes the parameter on parameter.yml
#         1.) open parameter.yml
#         2.) find this 'ses_train_score' lets says score to train
#         3.) find this 'ses_weekstart' please put the weekstart based on the latest monday date of month
#             lest says running time on desember the we will use november population then put the latest monday on november 
#             is 2020-11-30
#         5.) find this 'ses_low_path_to_save_hist' lets says 202010 to 202011
#         6.) find this 'ses_medium_path_to_save_hist' lets says 202010 to 202011
#         7.) find this 'ses_high_path_to_save_hist' lets says 202010 to 202011

# before running kmean clustering fit please get a number of cluster based on silhoutte score on the terminal after silhoute_analysis nodes then please put number cluster on parameter.yml, then find this 'ses_clustering_parameter' put n_cluster lets say 5
# ! kedro run --env=internal/ses --pipeline=ses_clustering --node=Kmeans_Clustering_fit_low
# ! kedro run --env=internal/ses --pipeline=ses_clustering --node=Kmeans_Clustering_fit_medium
# ! kedro run --env=internal/ses --pipeline=ses_clustering --node=Kmeans_Clustering_fit_high

# ## Fourth run scoring
# # noted : before running this phase please changes the table on catalog.yml
# #         1.) open catalog.yml
# #         2.) find this 'kmeans_low_score' lets says 202010 to 202011
# #         3.) find this 'kmeans_medium_score' lets says 202010 to 202011
# #         4.) find this 'kmeans_high_score' lets says 202010 to 202011
# #         5.) find this 'rfm_clustering_mapping_msisdn_segment_scoring' lets says 202010 to 202011 
# #         6.) additional important nodes when running nodes 
# #             a.)scoring_clus_low0 - scoring_clus_low99
# #             b.)scoring_clus_medium0 - scoring_clus_medium99
# #             c.)scoring_clus_high0 - scoring_clus_high99
# #             if still using clustering pickle on 202001 please just keep it continous but 
# #             if using new clustering pickles let says 202012 then open nodes.py 
# #             and get scoring_clus functions then please remove line 85 to 103 if using new pickle
# ! pip3 install scikit-learn==0.22.1
# ! kedro run --env=internal/ses --pipeline=ses_segmentation --node=rfm_step6
# ! kedro run --env=internal/ses --pipeline=ses_segmentation --node=rfm_step7
# ! kedro run --env=internal/ses --pipeline=ses_segmentation --node=selected_cols
# ! kedro run --env=internal/ses --pipeline=ses_segmentation --node=join_rfm_dmp_low
# ! kedro run --env=internal/ses --pipeline=ses_segmentation --node=join_rfm_dmp_medium
# ! kedro run --env=internal/ses --pipeline=ses_segmentation --node=join_rfm_dmp_high
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=Splitting_rfm_Data_sets_scoring_low
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=Splitting_rfm_Data_sets_scoring_medium
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=Splitting_rfm_Data_sets_scoring_high
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandaslow99
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_low99
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfslow99
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandasmedium99
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_medium99
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfsmedium99
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=PysparktoPandashigh99
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=scoring_clus_high99
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh0
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh1
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh2
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh3
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh4
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh5
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh6
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh7
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh8
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh9
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh10
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh11
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh12
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh13
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh14
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh15
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh16
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh17
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh18
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh19
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh20
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh21
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh22
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh23
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh24
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh25
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh26
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh27
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh28
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh29
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh30
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh31
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh32
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh33
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh34
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh35
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh36
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh37
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh38
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh39
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh40
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh41
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh42
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh43
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh44
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh45
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh46
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh47
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh48
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh49
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh50
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh51
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh52
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh53
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh54
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh55
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh56
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh57
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh58
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh59
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh60
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh61
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh62
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh63
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh64
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh65
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh66
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh67
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh68
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh69
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh70
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh71
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh72
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh73
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh74
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh75
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh76
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh77
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh78
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh79
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh80
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh81
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh82
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh83
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh84
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh85
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh86
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh87
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh88
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh89
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh90
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh91
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh92
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh93
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh94
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh95
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh96
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh97
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh98
# ! kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=hdfshigh99

# kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=concatenate_results_of_clustering_low
# kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=concatenate_results_of_clustering_medium
# kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=concatenate_results_of_clustering_high
# kedro run --env=internal/ses --pipeline=ses_clustering_scoring --node=concatenate_results_of_rfm_and_clustering 