# Copyright 2018-present QuantumBlack Visual Analytics Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
# NONINFRINGEMENT. IN NO EVENT WILL THE LICENSOR OR OTHER CONTRIBUTORS
# BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF, OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# The QuantumBlack Visual Analytics Limited ("QuantumBlack") name and logo
# (either separately or in combination, "QuantumBlack Trademarks") are
# trademarks of QuantumBlack. The License does not grant you any right or
# license to the QuantumBlack Trademarks. You may not use the QuantumBlack
# Trademarks or any confusingly similar mark as a trademark for your product,
#     or use the QuantumBlack Trademarks in any other manner that might cause
# confusion in the marketplace, including but not limited to in advertising,
# on websites, or on software.
#
# See the License for the specific language governing permissions and
# limitations under the License.

import datetime
from unittest import mock

import yaml
from pyspark.sql import SparkSession
from pyspark.sql.types import (
    ArrayType,
    DateType,
    DoubleType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
)

from src.dmp.pipelines.dmp._04_features.voice_calling.fea_voice_calling import (
    fea_voice_calling,
)
from src.tests.pysaprk_df_equality import assert_df_frame_equal


class TestFeatureVoiceCalling:
    config_feature = yaml.load(open("conf/dmp/training/parameters_feature.yml"))[
        "config_feature"
    ]
    required_output_features = yaml.load(
        open("conf/dmp/training/parameters_feature.yml")
    )["output_features"]

    @mock.patch(
        "src.dmp.pipelines.dmp._04_features.voice_calling.fea_voice_calling.get_start_date",
        return_value=datetime.date(2018, 10, 10),
        autospec=True,
    )
    @mock.patch(
        "src.dmp.pipelines.dmp._04_features.voice_calling.fea_voice_calling.get_end_date",
        return_value=datetime.date(2020, 10, 10),
        autospec=True,
    )
    def test_fea_inc_out_calls_usage(
        self, mock_get_start_date, mock_get_end_date, spark_session: SparkSession
    ):

        df_usage_mss_abt_dd = spark_session.createDataFrame(
            data=[
                [
                    "111",
                    datetime.date(2019, 7, 14),
                    100,
                    50,
                    20,
                    ["222", "333"],
                    ["555"],
                    ["222", "333", "555"],
                ],
                [
                    "111",
                    datetime.date(2019, 7, 21),
                    0,
                    0,
                    0,
                    ["222"],
                    ["444"],
                    ["222", "444"],
                ],
                ["111", datetime.date(2019, 7, 28), 50, 200, 0, ["444"], [], ["444"]],
                [
                    "222",
                    datetime.date(2019, 8, 5),
                    10,
                    0,
                    0,
                    ["666"],
                    ["444"],
                    ["666", "444"],
                ],
                ["222", datetime.date(2019, 8, 12), 0, None, 0, [], [], []],
                ["222", datetime.date(2019, 8, 19), 0, 0, 0, [], [], []],
                [
                    "222",
                    datetime.date(2019, 8, 26),
                    0,
                    50,
                    0,
                    ["888"],
                    ["777"],
                    ["888", "777"],
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), True),
                    StructField("weekstart", DateType(), True),
                    StructField("inc_call_dur", IntegerType(), True),
                    StructField("out_call_dur", IntegerType(), True),
                    StructField("total_dur_12_5_am", IntegerType(), True),
                    StructField("in_call_nums", ArrayType(StringType(), True), True),
                    StructField("out_call_nums", ArrayType(StringType(), True), True),
                    StructField(
                        "inc_out_call_nums", ArrayType(StringType(), True), True
                    ),
                ]
            ),
        )

        actual_result_df = fea_voice_calling(
            df_usage_mss_abt_dd,
            self.config_feature,
            "all",
            self.required_output_features,
        )

        expected_result_df = spark_session.createDataFrame(
            data=[
                [
                    "111",
                    datetime.date(2019, 7, 14),
                    20,
                    0,
                    2,
                    2,
                    150,
                    None,
                    150,
                    2,
                    3,
                    2,
                    3,
                    3,
                    100,
                    3,
                    2,
                    100,
                    1,
                    0.6666666666666666,
                    None,
                    3,
                    50,
                    1.0,
                    50,
                    100,
                    150,
                    50,
                    0.3333333333333333,
                    3,
                    0.6666666666666666,
                    2,
                    0.6666666666666666,
                    50,
                    3,
                    1,
                    1,
                    1,
                    2,
                    1,
                    3,
                    None,
                    2,
                    100,
                    150,
                    None,
                    3,
                    1,
                    100,
                    None,
                    150,
                    1,
                    3,
                    None,
                    3,
                    2,
                    0,
                    2,
                    2,
                    50,
                    2,
                    1,
                    150,
                    1,
                    100,
                    1,
                    3,
                    1,
                    1,
                    50,
                ],
                [
                    "111",
                    datetime.date(2019, 7, 21),
                    20,
                    1,
                    2,
                    3,
                    150,
                    0,
                    150,
                    2,
                    5,
                    3,
                    5,
                    4,
                    100,
                    5,
                    1,
                    0,
                    2,
                    0.6666666666666666,
                    None,
                    4,
                    50,
                    1.3333333333333333,
                    50,
                    100,
                    150,
                    50,
                    0.6666666666666666,
                    5,
                    0.6666666666666666,
                    3,
                    0.6,
                    50,
                    2,
                    2,
                    2,
                    1,
                    2,
                    2,
                    4,
                    None,
                    3,
                    100,
                    0,
                    None,
                    5,
                    2,
                    100,
                    0,
                    150,
                    1,
                    4,
                    None,
                    2,
                    3,
                    1,
                    1,
                    2,
                    0,
                    2,
                    2,
                    150,
                    2,
                    100,
                    2,
                    4,
                    2,
                    2,
                    50,
                ],
                [
                    "111",
                    datetime.date(2019, 7, 28),
                    20,
                    0,
                    3,
                    4,
                    400,
                    0,
                    250,
                    3,
                    6,
                    2,
                    6,
                    4,
                    150,
                    6,
                    1,
                    50,
                    2,
                    1.0,
                    None,
                    4,
                    250,
                    1.3333333333333333,
                    250,
                    150,
                    400,
                    200,
                    0.6666666666666666,
                    6,
                    0.375,
                    4,
                    0.6666666666666666,
                    250,
                    1,
                    2,
                    1,
                    0,
                    3,
                    2,
                    4,
                    None,
                    4,
                    150,
                    250,
                    None,
                    3,
                    2,
                    50,
                    0,
                    400,
                    0,
                    4,
                    None,
                    1,
                    4,
                    0,
                    1,
                    3,
                    200,
                    2,
                    2,
                    400,
                    2,
                    150,
                    2,
                    2,
                    2,
                    1,
                    250,
                ],
                [
                    "222",
                    datetime.date(2019, 8, 5),
                    0,
                    0,
                    1,
                    1,
                    10,
                    None,
                    10,
                    1,
                    2,
                    1,
                    2,
                    2,
                    10,
                    2,
                    1,
                    10,
                    1,
                    0.3333333333333333,
                    None,
                    2,
                    0,
                    0.6666666666666666,
                    0,
                    10,
                    10,
                    0,
                    0.3333333333333333,
                    2,
                    1.0,
                    1,
                    0.5,
                    0,
                    2,
                    1,
                    1,
                    1,
                    1,
                    1,
                    2,
                    None,
                    1,
                    10,
                    10,
                    None,
                    2,
                    1,
                    10,
                    None,
                    10,
                    1,
                    2,
                    None,
                    2,
                    1,
                    99999,
                    1,
                    1,
                    0,
                    1,
                    1,
                    10,
                    1,
                    10,
                    1,
                    2,
                    1,
                    1,
                    0,
                ],
                [
                    "222",
                    datetime.date(2019, 8, 12),
                    0,
                    1,
                    1,
                    1,
                    10,
                    0,
                    10,
                    1,
                    2,
                    1,
                    2,
                    2,
                    10,
                    2,
                    0,
                    0,
                    1,
                    0.3333333333333333,
                    None,
                    2,
                    0,
                    0.6666666666666666,
                    0,
                    10,
                    10,
                    0,
                    0.3333333333333333,
                    2,
                    1.0,
                    1,
                    0.5,
                    0,
                    0,
                    1,
                    1,
                    0,
                    1,
                    1,
                    2,
                    None,
                    1,
                    10,
                    None,
                    None,
                    2,
                    1,
                    10,
                    0,
                    10,
                    0,
                    2,
                    None,
                    0,
                    1,
                    99999,
                    0,
                    1,
                    None,
                    1,
                    1,
                    10,
                    1,
                    10,
                    1,
                    2,
                    1,
                    1,
                    0,
                ],
                [
                    "222",
                    datetime.date(2019, 8, 19),
                    0,
                    2,
                    1,
                    1,
                    10,
                    1,
                    0,
                    1,
                    2,
                    0,
                    2,
                    2,
                    10,
                    2,
                    0,
                    0,
                    1,
                    0.3333333333333333,
                    None,
                    2,
                    0,
                    0.6666666666666666,
                    0,
                    10,
                    10,
                    0,
                    0.3333333333333333,
                    2,
                    1.0,
                    1,
                    0.5,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    1,
                    2,
                    None,
                    1,
                    10,
                    0,
                    None,
                    0,
                    1,
                    0,
                    1,
                    10,
                    0,
                    2,
                    None,
                    0,
                    1,
                    99999,
                    0,
                    1,
                    0,
                    0,
                    1,
                    10,
                    1,
                    10,
                    1,
                    0,
                    1,
                    0,
                    0,
                ],
                [
                    "222",
                    datetime.date(2019, 8, 26),
                    0,
                    3,
                    2,
                    2,
                    50,
                    2,
                    50,
                    2,
                    4,
                    1,
                    2,
                    4,
                    10,
                    4,
                    1,
                    0,
                    1,
                    0.6666666666666666,
                    None,
                    2,
                    50,
                    1.3333333333333333,
                    50,
                    10,
                    60,
                    50,
                    0.6666666666666666,
                    4,
                    0.16666666666666666,
                    2,
                    0.5,
                    50,
                    2,
                    2,
                    1,
                    1,
                    1,
                    2,
                    4,
                    None,
                    1,
                    10,
                    50,
                    None,
                    2,
                    2,
                    0,
                    2,
                    60,
                    1,
                    4,
                    None,
                    2,
                    2,
                    0,
                    1,
                    2,
                    50,
                    1,
                    2,
                    60,
                    2,
                    0,
                    2,
                    2,
                    1,
                    1,
                    50,
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), True),
                    StructField("weekstart", DateType(), True),
                    StructField("fea_voice_tot_dur_12_5_am_03m", LongType(), True),
                    StructField(
                        "fea_voice_weeks_since_last_incoming_call", LongType(), True
                    ),
                    StructField(
                        "fea_voice_tot_uniq_inc_calls_02m", IntegerType(), True
                    ),
                    StructField("fea_voice_tot_inc_calls_01m", IntegerType(), True),
                    StructField("fea_voice_tot_call_dur_03w", LongType(), True),
                    StructField("fea_voice_not_any_out_call_1w_4w", LongType(), True),
                    StructField("fea_voice_tot_call_dur_02w", LongType(), True),
                    StructField(
                        "fea_voice_tot_uniq_inc_calls_01m", IntegerType(), True
                    ),
                    StructField("fea_voice_tot_calls_01m", IntegerType(), True),
                    StructField("fea_voice_tot_inc_calls_02w", IntegerType(), True),
                    StructField("fea_voice_tot_calls_03w", IntegerType(), True),
                    StructField("fea_voice_tot_uniq_calls_01m", IntegerType(), True),
                    StructField("fea_voice_inc_call_dur_02m", LongType(), True),
                    StructField("fea_voice_tot_calls_02m", IntegerType(), True),
                    StructField("fea_voice_tot_inc_calls_01w", IntegerType(), True),
                    StructField("fea_voice_inc_call_dur_01w", IntegerType(), True),
                    StructField("fea_voice_tot_out_calls_03w", IntegerType(), True),
                    StructField("fea_voice_avg_uniq_inc_call_03m", DoubleType(), True),
                    StructField("fea_voice_not_any_out_call_8w_12w", LongType(), True),
                    StructField("fea_voice_tot_uniq_calls_03w", IntegerType(), True),
                    StructField("fea_voice_out_call_dur_03m", LongType(), True),
                    StructField("fea_voice_avg_uniq_tot_call_03m", DoubleType(), True),
                    StructField("fea_voice_out_call_dur_01m", LongType(), True),
                    StructField("fea_voice_inc_call_dur_03m", LongType(), True),
                    StructField("fea_voice_tot_call_dur_03m", LongType(), True),
                    StructField("fea_voice_out_call_dur_02w", LongType(), True),
                    StructField("fea_voice_avg_uniq_out_call_03m", DoubleType(), True),
                    StructField("fea_voice_tot_calls_03m", IntegerType(), True),
                    StructField(
                        "fea_voice_inc_to_tot_calls_dur_03m", DoubleType(), True
                    ),
                    StructField("fea_voice_tot_inc_calls_02m", IntegerType(), True),
                    StructField(
                        "fea_voice_inc_to_tot_calls_num_03m", DoubleType(), True
                    ),
                    StructField("fea_voice_out_call_dur_03w", LongType(), True),
                    StructField("fea_voice_tot_calls_01w", IntegerType(), True),
                    StructField("fea_voice_tot_out_calls_02m", IntegerType(), True),
                    StructField(
                        "fea_voice_tot_uniq_out_calls_02w", IntegerType(), True
                    ),
                    StructField("fea_voice_tot_out_calls_01w", IntegerType(), True),
                    StructField(
                        "fea_voice_tot_uniq_inc_calls_03w", IntegerType(), True
                    ),
                    StructField("fea_voice_tot_out_calls_01m", IntegerType(), True),
                    StructField("fea_voice_tot_uniq_calls_02m", IntegerType(), True),
                    StructField("fea_voice_not_any_inc_call_8w_12w", LongType(), True),
                    StructField("fea_voice_tot_inc_calls_03w", IntegerType(), True),
                    StructField("fea_voice_inc_call_dur_01m", LongType(), True),
                    StructField("fea_voice_tot_call_dur_01w", IntegerType(), True),
                    StructField("fea_voice_not_any_out_call_4w_8w", LongType(), True),
                    StructField("fea_voice_tot_calls_02w", IntegerType(), True),
                    StructField(
                        "fea_voice_tot_uniq_out_calls_03m", IntegerType(), True
                    ),
                    StructField("fea_voice_inc_call_dur_02w", LongType(), True),
                    StructField("fea_voice_not_any_inc_call_1w_4w", LongType(), True),
                    StructField("fea_voice_tot_call_dur_01m", LongType(), True),
                    StructField(
                        "fea_voice_tot_uniq_out_calls_01w", IntegerType(), True
                    ),
                    StructField("fea_voice_tot_uniq_calls_03m", IntegerType(), True),
                    StructField("fea_voice_not_any_inc_call_4w_8w", LongType(), True),
                    StructField("fea_voice_tot_uniq_calls_01w", IntegerType(), True),
                    StructField("fea_voice_tot_inc_calls_03m", IntegerType(), True),
                    StructField(
                        "fea_voice_weeks_since_last_outgoing_call", LongType(), True
                    ),
                    StructField(
                        "fea_voice_tot_uniq_inc_calls_01w", IntegerType(), True
                    ),
                    StructField(
                        "fea_voice_tot_uniq_inc_calls_03m", IntegerType(), True
                    ),
                    StructField("fea_voice_out_call_dur_01w", IntegerType(), True),
                    StructField(
                        "fea_voice_tot_uniq_inc_calls_02w", IntegerType(), True
                    ),
                    StructField("fea_voice_tot_out_calls_03m", IntegerType(), True),
                    StructField("fea_voice_tot_call_dur_02m", LongType(), True),
                    StructField(
                        "fea_voice_tot_uniq_out_calls_01m", IntegerType(), True
                    ),
                    StructField("fea_voice_inc_call_dur_03w", LongType(), True),
                    StructField(
                        "fea_voice_tot_uniq_out_calls_02m", IntegerType(), True
                    ),
                    StructField("fea_voice_tot_uniq_calls_02w", IntegerType(), True),
                    StructField(
                        "fea_voice_tot_uniq_out_calls_03w", IntegerType(), True
                    ),
                    StructField("fea_voice_tot_out_calls_02w", IntegerType(), True),
                    StructField("fea_voice_out_call_dur_02m", LongType(), True),
                ]
            ),
        )

        assert_df_frame_equal(actual_result_df, expected_result_df)
