import datetime

import pyspark.sql.functions as f
from pyspark.sql import SparkSession
from pyspark.sql.types import (
    ArrayType,
    DateType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
)

from src.dmp.pipelines.dmp._01_aggregation.product.create_macro_product_weekly import (
    _weekly_aggregation as create_macro_product_weekly,
)
from src.dmp.pipelines.dmp._01_aggregation.product.create_macro_product_weekly import (
    union_macro_product_list,
)
from src.tests.pysaprk_df_equality import assert_df_frame_equal


class TestMacroproductAggregate:
    def test_macroproduct_weekly_aggregate(self, spark_session: SparkSession):
        sc = spark_session.sparkContext
        macroproduct_list = [
            "data0_dpi0_voice0to1200_sms1_val23to45",
            "data15to32_dpi1_voice1200to400000_sms0_val46plus",
            "data32to64_dpi0_voice0_sms0_val23to45",
            "data7to15_dpi0_voice0to1200_sms1_val23to45",
            "data3to7_dpi0_voice0_sms0_val5to10",
            "data7to15_dpi1_voice0_sms0_val23to45",
            "data0_dpi0_voice0_sms0_val0to4",
            "data3to7_dpi0_voice0to1200_sms0_val23to45",
            "data7to15_dpi0_voice0_sms0_val5to10",
            "data3to7_dpi0_voice0to1200_sms1_val23to45",
            "data15to32_dpi1_voice0to1200_sms1_val23to45",
            "data7to15_dpi0_voice0_sms0_val23to45",
            "data0to1_dpi0_voice1200to400000_sms0_val23to45",
            "data3to7_dpi0_voice0to1200_sms1_val5to10",
            "data7to15_dpi0_voice400000to999999999_sms1_val23to45",
            "data0_dpi0_voice0to1200_sms0_val0to4",
            "data3to7_dpi1_voice0_sms0_val23to45",
            "data7to15_dpi1_voice0to1200_sms1_val23to45",
            "data3to7_dpi1_voice0to1200_sms1_val23to45",
            "data1to3_dpi0_voice0to1200_sms0_val23to45",
            "data0_dpi0_voice400000to999999999_sms0_val0to4",
            "data0_dpi0_voice0_sms1_val5to10",
            "data15to32_dpi1_voice0_sms0_val23to45",
            "data0to1_dpi0_voice0to1200_sms1_val23to45",
            "data0_dpi0_voice1200to400000_sms0_val5to10",
            "data1to3_dpi0_voice0_sms0_val23to45",
            "data0to1_dpi0_voice0_sms0_val0to4",
            "data15to32_dpi0_voice0_sms0_val23to45",
            "data0_dpi0_voice1200to400000_sms0_val11to22",
            "data32to64_dpi0_voice0to1200_sms1_val23to45",
            "data1to3_dpi0_voice0_sms0_val0to4",
            "data7to15_dpi1_voice0to1200_sms0_val23to45",
            "data15to32_dpi0_voice0to1200_sms1_val23to45",
            "data32to64_dpi1_voice0_sms0_val23to45",
            "data1to3_dpi0_voice0to1200_sms1_val23to45",
            "data7to15_dpi0_voice0_sms0_val0to4",
            "data1to3_dpi0_voice0to1200_sms1_val5to10",
            "data3to7_dpi0_voice0_sms0_val23to45",
            "data15to32_dpi1_voice0to1200_sms0_val23to45",
            "data0to1_dpi0_voice0_sms0_val5to10",
            "data15to32_dpi1_voice0_sms0_val46plus",
            "data3to7_dpi1_voice0to1200_sms0_val23to45",
            "data15to32_dpi1_voice0_sms0_val5to10",
            "data0_dpi0_voice1200to400000_sms0_val23to45",
            "data7to15_dpi1_voice0to1200_sms0_val46plus",
            "data0to1_dpi0_voice0to1200_sms0_val5to10",
            "data3to7_dpi0_voice0_sms0_val0to4",
            "data32to64_dpi0_voice400000to999999999_sms1_val23to45",
            "data0_dpi0_voice0_sms0_val5to10",
            "data0to1_dpi0_voice1200to400000_sms0_val5to10",
            "data1to3_dpi0_voice0_sms0_val5to10",
        ]
        ifrs_schema = StructType(
            [
                StructField("msisdn", StringType()),
                StructField("event_date", StringType()),
                StructField("validity_period", IntegerType()),
                StructField("validity_period_unit", StringType()),
                StructField("transaction_id", StringType()),
                StructField("sigma_business_id", StringType()),
            ]
        )
        base_ifrs_c2p_dummy = sc.parallelize(
            [
                ("AAAAAA", "2020-03-03", 30, "days", "TR1", "000111",),
                ("AAAAAA", "2020-03-03", 60, "days", "TR2", "000444",),
                ("BBBBBB", "2020-03-03", 1, "months", "TR1", "000222",),
                ("AAAAAA", "2020-04-03", 30, "days", "TR1", "000222",),
                ("CCCCCC", "2020-03-03", 1, "year", "TR1", "000333",),
            ]
        )
        base_ifrs_c2p_reject_dummy = sc.parallelize(
            [("AAAAAA", "2020-02-03", 30, "days", "TR1", "000444",),]
        )
        bid_macroproduct_mapping_base_dummy = sc.parallelize(
            [
                ("000111", "data0to1_dpi0_voice0to1200_sms1_val23to45"),
                ("000222", "data0_dpi0_voice0_sms1_val5to10"),
            ]
        )
        bid_macroproduct_mapping_new_dummy = sc.parallelize(
            [
                ("000333", "data0_dpi0_voice0_sms1_val5to10", 0.2),
                ("000333", "data1to3_dpi0_voice0_sms0_val23to45", 0.3),
                ("000333", "data0_dpi0_voice0_sms1_val5to10", 0.2),
                ("000444", "data7to15_dpi1_voice0to1200_sms0_val23to45", 0.9),
                ("000444", "data15to32_dpi0_voice0to1200_sms1_val23to45", 0.1),
            ]
        )
        df_base_ifrs_c2p = spark_session.createDataFrame(
            base_ifrs_c2p_dummy, schema=ifrs_schema
        )
        df_base_ifrs_c2p_reject = spark_session.createDataFrame(
            base_ifrs_c2p_reject_dummy, schema=ifrs_schema
        )
        df_bid_macroproduct_mapping_base = spark_session.createDataFrame(
            bid_macroproduct_mapping_base_dummy,
            schema=StructType(
                [
                    StructField("bid", StringType()),
                    StructField("macroproduct", StringType()),
                ]
            ),
        )

        df_bid_macroproduct_mapping_new = spark_session.createDataFrame(
            bid_macroproduct_mapping_new_dummy,
            schema=StructType(
                [
                    StructField("bid", StringType()),
                    StructField("macroproduct", StringType()),
                    StructField("rev_share", FloatType()),
                ]
            ),
        )

        bid_macro_product_mapping_df = union_macro_product_list(
            df_bid_macroproduct_mapping_base, df_bid_macroproduct_mapping_new
        )

        select_cols = [
            "msisdn",
            "event_date",
            "validity_period",
            "validity_period_unit",
            "transaction_id",
            f.col("sigma_business_id").alias("bid"),
            f.concat("validity_period", f.lit(" "), "validity_period_unit").alias(
                "validity_period_str"
            ),
        ]
        df_base_ifrs_c2p = df_base_ifrs_c2p.select(select_cols)
        df_base_ifrs_c2p_reject = df_base_ifrs_c2p_reject.select(select_cols)

        actual_output = create_macro_product_weekly(
            df_base_ifrs_c2p,
            df_base_ifrs_c2p_reject,
            bid_macro_product_mapping_df,
            macroproduct_list,
        )
        # res_list = []
        # [j for j in i] for i in res.collect():
        #     res_list.append()

        expected_output = spark_session.createDataFrame(
            data=[
                [
                    "AAAAAA",
                    datetime.date(2020, 2, 10),
                    30.0,
                    30.0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    [["data7to15_dpi1_voice0to1200_sms0_val23to45", "1", "30.0"]],
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    "AAAAAA",
                    datetime.date(2020, 3, 9),
                    30.0,
                    60.0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    [
                        ["data0to1_dpi0_voice0to1200_sms1_val23to45", "1", "30.0"],
                        ["data7to15_dpi1_voice0to1200_sms0_val23to45", "1", "60.0"],
                    ],
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    "AAAAAA",
                    datetime.date(2020, 4, 6),
                    30.0,
                    30.0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    [["data0_dpi0_voice0_sms1_val5to10", "1", "30.0"]],
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    "BBBBBB",
                    datetime.date(2020, 3, 9),
                    30.0,
                    30.0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    [["data0_dpi0_voice0_sms1_val5to10", "1", "30.0"]],
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    "CCCCCC",
                    datetime.date(2020, 3, 9),
                    365.0,
                    365.0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    [["data1to3_dpi0_voice0_sms0_val23to45", "1", "365.0"]],
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("weekstart", DateType(), False),
                    StructField(
                        "fea_product_min_validity_period_days_01w", DoubleType(), True
                    ),
                    StructField(
                        "fea_product_max_validity_period_days_01w", DoubleType(), True
                    ),
                    StructField(
                        "fea_product_count_validity_1_to_4_days_01w", LongType(), True
                    ),
                    StructField(
                        "fea_product_count_validity_5_to_10_days_01w", LongType(), True
                    ),
                    StructField(
                        "fea_product_count_validity_11_to_22_days_01w", LongType(), True
                    ),
                    StructField(
                        "fea_product_count_validity_23_to_45_days_01w", LongType(), True
                    ),
                    StructField(
                        "fea_product_count_validity_46plus_days_01w", LongType(), True
                    ),
                    StructField(
                        "macroproduct_count_list",
                        ArrayType(ArrayType(StringType(), True), True),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0_dpi0_voice0to1200_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data15to32_dpi1_voice1200to400000_sms0_val46plus_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data32to64_dpi0_voice0_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data7to15_dpi0_voice0to1200_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data3to7_dpi0_voice0_sms0_val5to10_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data7to15_dpi1_voice0_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0_dpi0_voice0_sms0_val0to4_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data3to7_dpi0_voice0to1200_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data7to15_dpi0_voice0_sms0_val5to10_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data3to7_dpi0_voice0to1200_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data15to32_dpi1_voice0to1200_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data7to15_dpi0_voice0_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0to1_dpi0_voice1200to400000_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data3to7_dpi0_voice0to1200_sms1_val5to10_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data7to15_dpi0_voice400000to999999999_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0_dpi0_voice0to1200_sms0_val0to4_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data3to7_dpi1_voice0_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data7to15_dpi1_voice0to1200_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data3to7_dpi1_voice0to1200_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data1to3_dpi0_voice0to1200_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0_dpi0_voice400000to999999999_sms0_val0to4_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0_dpi0_voice0_sms1_val5to10_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data15to32_dpi1_voice0_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0to1_dpi0_voice0to1200_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0_dpi0_voice1200to400000_sms0_val5to10_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data1to3_dpi0_voice0_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0to1_dpi0_voice0_sms0_val0to4_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data15to32_dpi0_voice0_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0_dpi0_voice1200to400000_sms0_val11to22_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data32to64_dpi0_voice0to1200_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data1to3_dpi0_voice0_sms0_val0to4_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data7to15_dpi1_voice0to1200_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data15to32_dpi0_voice0to1200_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data32to64_dpi1_voice0_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data1to3_dpi0_voice0to1200_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data7to15_dpi0_voice0_sms0_val0to4_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data1to3_dpi0_voice0to1200_sms1_val5to10_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data3to7_dpi0_voice0_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data15to32_dpi1_voice0to1200_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0to1_dpi0_voice0_sms0_val5to10_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data15to32_dpi1_voice0_sms0_val46plus_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data3to7_dpi1_voice0to1200_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data15to32_dpi1_voice0_sms0_val5to10_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0_dpi0_voice1200to400000_sms0_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data7to15_dpi1_voice0to1200_sms0_val46plus_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0to1_dpi0_voice0to1200_sms0_val5to10_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data3to7_dpi0_voice0_sms0_val0to4_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data32to64_dpi0_voice400000to999999999_sms1_val23to45_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0_dpi0_voice0_sms0_val5to10_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data0to1_dpi0_voice1200to400000_sms0_val5to10_01w",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_product_count_data1to3_dpi0_voice0_sms0_val5to10_01w",
                        LongType(),
                        True,
                    ),
                ]
            ),
        )
        assert_df_frame_equal(actual_output, expected_output)
