# Copyright 2018-present QuantumBlack Visual Analytics Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
# NONINFRINGEMENT. IN NO EVENT WILL THE LICENSOR OR OTHER CONTRIBUTORS
# BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF, OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# The QuantumBlack Visual Analytics Limited ("QuantumBlack") name and logo
# (either separately or in combination, "QuantumBlack Trademarks") are
# trademarks of QuantumBlack. The License does not grant you any right or
# license to the QuantumBlack Trademarks. You may not use the QuantumBlack
# Trademarks or any confusingly similar mark as a trademark for your product,
#     or use the QuantumBlack Trademarks in any other manner that might cause
# confusion in the marketplace, including but not limited to in advertising,
# on websites, or on software.
#
# See the License for the specific language governing permissions and
# limitations under the License.

WINDOWS_MAPPING = {
    7: "01w",
    28: "01m",
    91: "03m",
}

OUTPUT_COLUMNS_NON_MACRO = [
    "msisdn",
    "weekstart",
    "fea_allowance_4g_data_pool_sum_01w",
    "fea_allowance_4g_data_pool_sum_01m",
    "fea_allowance_4g_data_pool_sum_03m",
    "fea_allowance_data_4g_mds_sum_01w",
    "fea_allowance_data_4g_mds_sum_01m",
    "fea_allowance_data_4g_mds_sum_03m",
    "fea_allowance_data_4g_omg_sum_01w",
    "fea_allowance_data_4g_omg_sum_01m",
    "fea_allowance_data_4g_omg_sum_03m",
    "fea_allowance_data_4g_sum_01w",
    "fea_allowance_data_4g_sum_01m",
    "fea_allowance_data_4g_sum_03m",
    "fea_allowance_data_allnet_local_sum_01w",
    "fea_allowance_data_allnet_local_sum_01m",
    "fea_allowance_data_allnet_local_sum_03m",
    "fea_allowance_data_allnet_siang_sum_01w",
    "fea_allowance_data_allnet_siang_sum_01m",
    "fea_allowance_data_allnet_siang_sum_03m",
    "fea_allowance_data_allnet_sum_01w",
    "fea_allowance_data_allnet_sum_01m",
    "fea_allowance_data_allnet_sum_03m",
    "fea_allowance_data_dpi_sum_01w",
    "fea_allowance_data_dpi_sum_01m",
    "fea_allowance_data_dpi_sum_03m",
    "fea_allowance_data_games_sum_01w",
    "fea_allowance_data_games_sum_01m",
    "fea_allowance_data_games_sum_03m",
    "fea_allowance_data_mds_sum_01w",
    "fea_allowance_data_mds_sum_01m",
    "fea_allowance_data_mds_sum_03m",
    "fea_allowance_data_music_sum_01w",
    "fea_allowance_data_music_sum_01m",
    "fea_allowance_data_music_sum_03m",
    "fea_allowance_data_onnet_sum_01w",
    "fea_allowance_data_onnet_sum_01m",
    "fea_allowance_data_onnet_sum_03m",
    "fea_allowance_data_roaming_sum_01w",
    "fea_allowance_data_roaming_sum_01m",
    "fea_allowance_data_roaming_sum_03m",
    "fea_allowance_data_video_sum_01w",
    "fea_allowance_data_video_sum_01m",
    "fea_allowance_data_video_sum_03m",
    "fea_allowance_data_wifi_sum_01w",
    "fea_allowance_data_wifi_sum_01m",
    "fea_allowance_data_wifi_sum_03m",
    "fea_allowance_monbal_monbal_sum_01w",
    "fea_allowance_monbal_monbal_sum_01m",
    "fea_allowance_monbal_monbal_sum_03m",
    "fea_allowance_monbal_onnet_sum_01w",
    "fea_allowance_monbal_onnet_sum_01m",
    "fea_allowance_monbal_onnet_sum_03m",
    "fea_allowance_monbal_siang_sum_01w",
    "fea_allowance_monbal_siang_sum_01m",
    "fea_allowance_monbal_siang_sum_03m",
    "fea_allowance_sms_allnet_sum_01w",
    "fea_allowance_sms_allnet_sum_01m",
    "fea_allowance_sms_allnet_sum_03m",
    "fea_allowance_sms_allopr_sum_01w",
    "fea_allowance_sms_allopr_sum_01m",
    "fea_allowance_sms_allopr_sum_03m",
    "fea_allowance_sms_offnet_sum_01w",
    "fea_allowance_sms_offnet_sum_01m",
    "fea_allowance_sms_offnet_sum_03m",
    "fea_allowance_sms_onnet_siang_sum_01w",
    "fea_allowance_sms_onnet_siang_sum_01m",
    "fea_allowance_sms_onnet_siang_sum_03m",
    "fea_allowance_sms_onnet_sum_01w",
    "fea_allowance_sms_onnet_sum_01m",
    "fea_allowance_sms_onnet_sum_03m",
    "fea_allowance_sms_roaming_sum_01w",
    "fea_allowance_sms_roaming_sum_01m",
    "fea_allowance_sms_roaming_sum_03m",
    "fea_allowance_subscription_bein_sum_01w",
    "fea_allowance_subscription_bein_sum_01m",
    "fea_allowance_subscription_bein_sum_03m",
    "fea_allowance_subscription_hooq_sum_01w",
    "fea_allowance_subscription_hooq_sum_01m",
    "fea_allowance_subscription_hooq_sum_03m",
    "fea_allowance_subscription_music_sum_01w",
    "fea_allowance_subscription_music_sum_01m",
    "fea_allowance_subscription_music_sum_03m",
    "fea_allowance_subscription_tribe_sum_01w",
    "fea_allowance_subscription_tribe_sum_01m",
    "fea_allowance_subscription_tribe_sum_03m",
    "fea_allowance_subscription_viu_sum_01w",
    "fea_allowance_subscription_viu_sum_01m",
    "fea_allowance_subscription_viu_sum_03m",
    "fea_allowance_tcash_balance_sum_01w",
    "fea_allowance_tcash_balance_sum_01m",
    "fea_allowance_tcash_balance_sum_03m",
    "fea_allowance_unlimited_data_sum_01w",
    "fea_allowance_unlimited_data_sum_01m",
    "fea_allowance_unlimited_data_sum_03m",
    "fea_allowance_voice_allnet_sum_01w",
    "fea_allowance_voice_allnet_sum_01m",
    "fea_allowance_voice_allnet_sum_03m",
    "fea_allowance_voice_allopr_sum_01w",
    "fea_allowance_voice_allopr_sum_01m",
    "fea_allowance_voice_allopr_sum_03m",
    "fea_allowance_voice_idd_sum_01w",
    "fea_allowance_voice_idd_sum_01m",
    "fea_allowance_voice_idd_sum_03m",
    "fea_allowance_voice_offnet_sum_01w",
    "fea_allowance_voice_offnet_sum_01m",
    "fea_allowance_voice_offnet_sum_03m",
    "fea_allowance_voice_onnet_malam_sum_01w",
    "fea_allowance_voice_onnet_malam_sum_01m",
    "fea_allowance_voice_onnet_malam_sum_03m",
    "fea_allowance_voice_onnet_siang_sum_01w",
    "fea_allowance_voice_onnet_siang_sum_01m",
    "fea_allowance_voice_onnet_siang_sum_03m",
    "fea_allowance_voice_onnet_sum_01w",
    "fea_allowance_voice_onnet_sum_01m",
    "fea_allowance_voice_onnet_sum_03m",
    "fea_allowance_voice_roaming_mo_sum_01w",
    "fea_allowance_voice_roaming_mo_sum_01m",
    "fea_allowance_voice_roaming_mo_sum_03m",
    "fea_allowance_voice_roaming_sum_01w",
    "fea_allowance_voice_roaming_sum_01m",
    "fea_allowance_voice_roaming_sum_03m",
    "fea_revenue_sum_01w",
    "fea_revenue_sum_01m",
    "fea_revenue_sum_03m",
]
