columns_of_interest:
  - "fea_handset_count_04m"
  - "fea_int_app_usage_adult_sites_data_vol_03m"
  - "fea_int_app_usage_credit_lending_company_accessed_apps_03m"
  - "fea_int_app_usage_credit_lending_company_data_vol_03m"
  - "fea_int_app_usage_ecommerce_data_vol_03m"
  - "fea_int_app_usage_expensive_hobby_data_vol_03m"
  - "fea_int_app_usage_gambling_data_vol_03m"
  - "fea_int_app_usage_mobile_wallets_data_vol_03m"
  - "fea_int_app_usage_multifinance_accessed_apps_03m"
  - "fea_int_app_usage_multifinance_data_vol_03m"
  - "fea_int_app_usage_travel_data_vol_03m"
  - "fea_int_usage_non_zero_usage_days_03m"
  - "fea_int_usage_num_days_with_total_data_usage_above_2mb_03m"
  - "fea_int_usage_tot_trx_night_03m"
  - "fea_int_usage_weekend_kb_usage_03m"
  - "fea_int_usage_zero_usage_days_03m"
  - "fea_los"
  - "fea_rech_tot_amt_avg_03m"
  - "fea_rech_tot_trx_sum_03m"
  - "fea_rech_trx_pkg_prchse_stddev_03m"
  - "fea_rev_tot_sum_02m"
  - "fea_rev_voice_tot_sum_03m"
  - "fea_txt_msg_banks_incoming_count_03m"
  - "fea_txt_msg_banks_unique_senders_count_03m"
  - "fea_txt_msg_count_03m"
  - "fea_txt_msg_credit_lending_companies_incoming_count_03m"
  - "fea_txt_msg_credit_lending_companies_unique_senders_count_03m"
  - "fea_txt_msg_entertainment_unique_senders_count_03m"
  - "fea_txt_msg_incoming_count_03m"
  - "fea_txt_msg_media_incoming_count_03m"
  - "fea_txt_msg_media_unique_senders_count_03m"
  - "fea_txt_msg_mobile_wallets_unique_senders_count_03m"
  - "fea_txt_msg_multifinance_incoming_count_03m"
  - "fea_txt_msg_multifinance_unique_senders_count_03m"
  - "fea_txt_msg_outgoing_count_03m"
  - "fea_txt_msg_retail_incoming_count_03m"
  - "fea_txt_msg_retail_unique_senders_count_03m"
  - "fea_txt_msg_travel_company_unique_senders_count_03m"
  - "fea_txt_msg_voice_ratio_incoming_03m"
  - "fea_voice_avg_uniq_out_call_03m"
  - "fea_voice_tot_dur_12_5_am_03m"
  - "fea_voice_tot_uniq_out_calls_03m"
  - "flag_fstqpd30"

class_column_name: "flag_fstqpd30"
max_bin: 5
score_column_name: "default_probability_score"
score_num_of_bins: 7

filter_dataset: true
filter_column: weekstart
first_period: "2019-06-17"
last_period: "2019-08-19"