hdfs_base_path: hdfs:///data/landing/dmp_production/ # HDFS Base Path

features_binning:
  default_probability_score:
    0:
      max: 0.020621169039208603
      min: -inf
      proportion: 0.0851
    1:
      max: 0.03599647842265289
      min: 0.020621169039208603
      proportion: 0.1289
    2:
      max: 0.058782867600817135
      min: 0.03599647842265289
      proportion: 0.1775
    3:
      max: 0.10794895104176262
      min: 0.058782867600817135
      proportion: 0.3184
    4:
      max: inf
      min: 0.10794895104176262
      proportion: 0.2901
  fea_handset_count_04m:
    0:
      max: 1.5
      min: -inf
      proportion: 0.7096
    1:
      max: 2.5
      min: 1.5
      proportion: 0.1837
    2:
      max: 3.5
      min: 2.5
      proportion: 0.0641
    3:
      max: inf
      min: 3.5
      proportion: 0.0427
  fea_int_app_usage_credit_lending_company_accessed_apps_03m:
    0:
      max: 0.5
      min: -inf
      proportion: 0.9647
    1:
      max: 1.5
      min: 0.5
      proportion: 0.0271
    2:
      max: inf
      min: 1.5
      proportion: 0.0081
  fea_int_app_usage_credit_lending_company_data_vol_03m:
    0:
      max: 100585.5
      min: -inf
      proportion: 0.976
    1:
      max: 2080348.5
      min: 100585.5
      proportion: 0.0134
    2:
      max: inf
      min: 2080348.5
      proportion: 0.0106
  fea_int_app_usage_ecommerce_data_vol_03m:
    0:
      max: 3808025.5
      min: -inf
      proportion: 0.7988
    1:
      max: 12790773.5
      min: 3808025.5
      proportion: 0.0562
    2:
      max: 66861618.0
      min: 12790773.5
      proportion: 0.0704
    3:
      max: 285152320.0
      min: 66861618.0
      proportion: 0.0441
    4:
      max: inf
      min: 285152320.0
      proportion: 0.0305
  fea_int_app_usage_gambling_data_vol_03m:
    0:
      max: 86.0
      min: -inf
      proportion: 0.8116
    1:
      max: 151476.0
      min: 86.0
      proportion: 0.0973
    2:
      max: 412228.5
      min: 151476.0
      proportion: 0.0358
    3:
      max: 2583387.0
      min: 412228.5
      proportion: 0.0359
    4:
      max: inf
      min: 2583387.0
      proportion: 0.0193
  fea_int_app_usage_mobile_wallets_data_vol_03m:
    0:
      max: 9349.5
      min: -inf
      proportion: 0.8103
    1:
      max: 124148.5
      min: 9349.5
      proportion: 0.0855
    2:
      max: 875773.0
      min: 124148.5
      proportion: 0.0445
    3:
      max: 13760477.0
      min: 875773.0
      proportion: 0.0445
    4:
      max: inf
      min: 13760477.0
      proportion: 0.0152
  fea_int_app_usage_multifinance_accessed_apps_03m:
    0:
      max: 0.5
      min: -inf
      proportion: 0.9912
    1:
      max: inf
      min: 0.5
      proportion: 0.0088
  fea_int_usage_non_zero_usage_days_03m:
    0:
      max: 0.5
      min: -inf
      proportion: 0.4085
    1:
      max: 61.5
      min: 0.5
      proportion: 0.3609
    2:
      max: 86.5
      min: 61.5
      proportion: 0.0849
    3:
      max: 90.5
      min: 86.5
      proportion: 0.042
    4:
      max: inf
      min: 90.5
      proportion: 0.1038
  fea_int_usage_num_days_with_total_data_usage_above_2mb_03m:
    0:
      max: 29.5
      min: -inf
      proportion: 0.7298
    1:
      max: 73.5
      min: 29.5
      proportion: 0.1273
    2:
      max: 83.5
      min: 73.5
      proportion: 0.037
    3:
      max: 90.5
      min: 83.5
      proportion: 0.0566
    4:
      max: inf
      min: 90.5
      proportion: 0.0493
  fea_los:
    0:
      max: 231.5
      min: -inf
      proportion: 0.3653
    1:
      max: 1037.5
      min: 231.5
      proportion: 0.2921
    2:
      max: 2876.5
      min: 1037.5
      proportion: 0.2335
    3:
      max: 3976.5
      min: 2876.5
      proportion: 0.0641
    4:
      max: inf
      min: 3976.5
      proportion: 0.045
  fea_rech_tot_amt_avg_03m:
    0:
      max: 19960.76953125
      min: -inf
      proportion: 0.6311
    1:
      max: 28307.0712890625
      min: 19960.76953125
      proportion: 0.1296
    2:
      max: 43613.24609375
      min: 28307.0712890625
      proportion: 0.0902
    3:
      max: 67011.90625
      min: 43613.24609375
      proportion: 0.0837
    4:
      max: inf
      min: 67011.90625
      proportion: 0.0653
  fea_rech_tot_trx_sum_03m:
    0:
      max: 0.5
      min: -inf
      proportion: 0.2139
    1:
      max: 9.5
      min: 0.5
      proportion: 0.6122
    2:
      max: 13.5
      min: 9.5
      proportion: 0.0731
    3:
      max: 24.5
      min: 13.5
      proportion: 0.0698
    4:
      max: inf
      min: 24.5
      proportion: 0.0309
  fea_rev_tot_sum_02m:
    0:
      max: 9872.5
      min: -inf
      proportion: 0.3548
    1:
      max: 15335.5
      min: 9872.5
      proportion: 0.0632
    2:
      max: 40030.5
      min: 15335.5
      proportion: 0.169
    3:
      max: 152008.0
      min: 40030.5
      proportion: 0.2588
    4:
      max: inf
      min: 152008.0
      proportion: 0.1543
  fea_rev_voice_tot_sum_03m:
    0:
      max: 647.5
      min: -inf
      proportion: 0.4186
    1:
      max: 4302.5
      min: 647.5
      proportion: 0.0723
    2:
      max: 92350.5
      min: 4302.5
      proportion: 0.3944
    3:
      max: 258917.5
      min: 92350.5
      proportion: 0.0902
    4:
      max: inf
      min: 258917.5
      proportion: 0.0245
  fea_txt_msg_banks_incoming_count_03m:
    0:
      max: 0.5
      min: -inf
      proportion: 0.9108
    1:
      max: 5.5
      min: 0.5
      proportion: 0.0374
    2:
      max: 22.5
      min: 5.5
      proportion: 0.0264
    3:
      max: inf
      min: 22.5
      proportion: 0.0253
  fea_txt_msg_credit_lending_companies_unique_senders_count_03m:
    0:
      max: 0.5
      min: -inf
      proportion: 0.9675
    1:
      max: 2.5
      min: 0.5
      proportion: 0.0283
    2:
      max: inf
      min: 2.5
      proportion: 0.0042
  fea_txt_msg_incoming_count_03m:
    0:
      max: 99.5
      min: -inf
      proportion: 0.3948
    1:
      max: 453.5
      min: 99.5
      proportion: 0.4385
    2:
      max: 694.5
      min: 453.5
      proportion: 0.0842
    3:
      max: 1209.5
      min: 694.5
      proportion: 0.0512
    4:
      max: inf
      min: 1209.5
      proportion: 0.0313
  fea_txt_msg_multifinance_incoming_count_03m:
    0:
      max: 1.5
      min: -inf
      proportion: 0.9809
    1:
      max: 5.5
      min: 1.5
      proportion: 0.0096
    2:
      max: 10.5
      min: 5.5
      proportion: 0.0038
    3:
      max: inf
      min: 10.5
      proportion: 0.0056
  fea_txt_msg_outgoing_count_03m:
    0:
      max: 27.5
      min: -inf
      proportion: 0.7091
    1:
      max: 47.5
      min: 27.5
      proportion: 0.0798
    2:
      max: 78.5
      min: 47.5
      proportion: 0.0617
    3:
      max: 104.5
      min: 78.5
      proportion: 0.0289
    4:
      max: inf
      min: 104.5
      proportion: 0.1204
  fea_voice_tot_dur_12_5_am_03m:
    0:
      max: 5.5
      min: -inf
      proportion: 0.2655
    1:
      max: 117.5
      min: 5.5
      proportion: 0.4296
    2:
      max: 682.5
      min: 117.5
      proportion: 0.1691
    3:
      max: 4962.5
      min: 682.5
      proportion: 0.0948
    4:
      max: inf
      min: 4962.5
      proportion: 0.041
  fea_voice_tot_uniq_out_calls_03m:
    0:
      max: 5.5
      min: -inf
      proportion: 0.491
    1:
      max: 14.5
      min: 5.5
      proportion: 0.1777
    2:
      max: 42.5
      min: 14.5
      proportion: 0.2075
    3:
      max: 143.5
      min: 42.5
      proportion: 0.1112
    4:
      max: inf
      min: 143.5
      proportion: 0.0126

columns_to_include:
  - "weekstart"
  - "dimension"
  - "bins"
  - "proportion_baseline"
  - "proportion_current"
  - "psi"
