pai_run_name: "churn_6_weeks_propensity_network_product"
pai_tags:
  - "Churn"
  - "Propensity"
  - "Network product"

# no campaign names implies every person is non taker
campaign_names:

# Target definition
use_case: "churn"
target_source:
  pai_workaround: >
    case
        when (fea_txt_msg_outgoing_count_01w > 0)
            or (fea_voice_tot_out_calls_01w > 0)
            or (fea_int_usage_tot_kb_data_usage_01w > 0)
            or (fea_rev_dls_ussd_payu_sum_01w > 0)
            or (fea_revenue_sum_01w > 0)
        then 0
        else 1
    end

target_window_weeks: 6
train_offset_weeks: 3
training_date: '2020-05-25'

inactivity_length: 6

column_selection:
  required:
    - fea_custprof_brand
    - fea_custprof_los
    - fea_custprof_persona_los
    - fea_custprof_segment_hvc_m1
    - fea_custprof_segment_hvc_mtd
    - fea_handset_changed_count_01m
    - fea_int_app_usage_ecommerce_data_vol_01w,
    - fea_int_app_usage_social_media_sites_data_vol_01m,
    - fea_int_app_usage_video_days_since_last_usage,
    - fea_int_usage_med_4g_data_usage_03m,
    - fea_int_usage_tot_kb_data_usage_01w,
    - fea_los,
    - fea_network_ccsr_ps_avg_1m,
    - fea_network_ccsr_ps_avg_1w,
    - fea_network_cssr_ps_avg_1m,
    - fea_network_cssr_ps_avg_1w,
    - fea_network_downlink_traffic_volume_mb_avg_1m,
    - fea_network_downlink_traffic_volume_mb_avg_1w,
    - fea_network_downlink_traffic_volume_mb_avg_2m,
    - fea_network_downlink_traffic_volume_mb_avg_2w,
    - fea_network_downlink_traffic_volume_mb_avg_3m,
    - fea_network_downlink_traffic_volume_mb_avg_3w,
    - fea_network_downlink_traffic_volume_mb_avg_6m,
    - fea_network_edge_mbyte_avg_1m,
    - fea_network_edge_mbyte_avg_1w,
    - fea_network_gprs_mbyte_avg_1m,
    - fea_network_gprs_mbyte_avg_1w,
    - fea_network_hosr_denum_sum_avg_1m,
    - fea_network_hosr_denum_sum_avg_1w,
    - fea_network_hosr_num_sum_avg_1m,
    - fea_network_hosr_num_sum_avg_1w,
    - fea_network_hsdpa_accesability_avg_1m,
    - fea_network_hsdpa_accesability_avg_1w,
    - fea_network_hsupa_accesability_avg_1m,
    - fea_network_hsupa_accesability_avg_1w,
    - fea_network_hsupa_mean_user_avg_1m,
    - fea_network_hsupa_mean_user_avg_1m_m,
    - fea_network_hsupa_mean_user_avg_1w,
    - fea_network_hsupa_mean_user_avg_1w_m,
    - fea_network_max_occupancy_pct_avg_1m,
    - fea_network_max_occupancy_pct_avg_1w,
    - fea_network_payload_hspa_mbyte_avg_1m,
    - fea_network_payload_hspa_mbyte_avg_1w,
    - fea_network_payload_psr99_mbyte_avg_1m,
    - fea_network_payload_psr99_mbyte_avg_1w,
    - fea_network_total_payload_mb_avg_1m,
    - fea_network_total_payload_mb_avg_1w,
    - fea_network_total_throughput_kbps_avg_1m,
    - fea_network_total_throughput_kbps_avg_1w,
    - fea_network_volume_voice_traffic_erl_avg_1m,
    - fea_network_volume_voice_traffic_erl_avg_1w,
    - fea_network_volume_voice_traffic_erl_avg_2m,
    - fea_network_volume_voice_traffic_erl_avg_2w,
    - fea_network_volume_voice_traffic_erl_avg_3m,
    - fea_network_volume_voice_traffic_erl_avg_3w,
    - fea_network_volume_voice_traffic_erl_avg_6m,
    - fea_product_count_data0_dpi0_voice0to1200_sms0_val0to4_01m,
    - fea_product_count_data0to1_dpi0_voice0_sms0_val5to10_01m,
    - fea_product_count_data15to32_dpi0_voice0_sms0_val23to45_01m,
    - fea_product_count_data15to32_dpi0_voice0to1200_sms1_val23to45_01m,
    - fea_product_count_data15to32_dpi1_voice0_sms0_val23to45_01m,
    - fea_product_count_data15to32_dpi1_voice0to1200_sms1_val23to45_01m,
    - fea_product_count_data1to3_dpi0_voice0_sms0_val23to45_01m,
    - fea_product_count_data1to3_dpi0_voice0to1200_sms1_val23to45_01m,
    - fea_product_count_data32to64_dpi0_voice0to1200_sms1_val23to45_01m,
    - fea_product_count_data32to64_dpi1_voice0_sms0_val23to45_01m,
    - fea_product_count_data3to7_dpi0_voice0_sms0_val23to45_01m,
    - fea_product_count_data3to7_dpi0_voice0to1200_sms1_val23to45_01m,
    - fea_product_count_data3to7_dpi1_voice0_sms0_val23to45_01m,
    - fea_product_count_data7to15_dpi0_voice0_sms0_val23to45_01m,
    - fea_product_count_data7to15_dpi0_voice0to1200_sms1_val23to45_01m,
    - fea_product_count_data7to15_dpi1_voice0_sms0_val23to45_01m,
    - fea_product_count_data7to15_dpi1_voice0to1200_sms0_val23to45_01m,
    - fea_product_count_data7to15_dpi1_voice0to1200_sms0_val46plus_01m,
    - fea_product_count_data7to15_dpi1_voice0to1200_sms1_val23to45_01m,
    - fea_product_count_validity_11_to_22_days_01m,
    - fea_product_count_validity_1_to_4_days_01m,
    - fea_product_count_validity_23_to_45_days_01m,
    - fea_product_count_validity_46plus_days_01m,
    - fea_product_count_validity_5_to_10_days_01m,
    - fea_product_max_validity_period_days_01m,
    - fea_product_min_validity_period_days_01m,
    - fea_product_total_activated_product_01m,
    - fea_product_total_active_product,
    - fea_product_total_product_changes_01m,
    - fea_rev_roam_payu_sum_03m
    - fea_rev_roam_payu_sum_03m
    - fea_rev_roam_payu_sum_03m
    - fea_revenue_sum_01m
    - fea_txt_msg_outgoing_count_01w
    - fea_voice_tot_out_calls_01w
    - fea_voice_tot_uniq_out_calls_03m
  excluded: []
  exclude_dtype_prefix:
    - "string"
    - "array"
  exclude_suffix:
    - "_03w"
    - "_02m"
  exclude_prefix: []

# Segment definition - model will be trained on a subset of users
# must be a valid sql statement
extra_filter:

# Sampling: empty value disables sampling
n_rows_to_sample: 100_000
n_features_to_sample:

# Column names
feature_column_prefix: "fea_"
msisdn_column: "msisdn"
campaign_start_date_column: "start_date"
campaign_end_date_column: "end_date"
weekstart_column: "weekstart"
campaign_name_column: "campaign_name"
is_control_column: "is_control"
is_taker_column: "is_taker"

# Kedro/PAI settings
use_spark: True
use_pai_logging: True

pai_experiment: "Model factory"
pai_username: "Test"
pai_personal_runs: "hdfs:///data/landing/dmp_remote/model-factory/{USER}"

# Plots labels
plot_labels:
  target_component_y_label: "Average component value"

# PDP features to plot
pdp_features:
  - [fea_int_app_usage_ecommerce_data_vol_01w]
  - [fea_int_app_usage_social_media_sites_data_vol_01m]

# Churn comparison plots
plot_churn_comparison_features:
  - "fea_int_app_usage_social_media_sites_data_vol_01m"

# Propensity model parameters
propensity_preprocessing_blacklisted_columns:
  - msisdn
propensity_training_ratio: 0.8

# SHAP treatment vs control parameters
shap_treatment_vs_control:
  n_folds: 5
  n_iterations: 100
  train_frac: 0.8
  n_features: 15

survival_plots:
  - col: fea_los
