hdfs_base_path: hdfs:///data/landing/dmp_production/ # HDFS Base Path

features_binning:
  raw_default_probability_score:
    0:
      count: 827
      max: 0.02092912363039602
      mean: 0.0148
      min: -inf
      proportion: 0.0052
    1:
      count: 827
      max: 0.03143614639713355
      mean: 0.0261
      min: 0.02092912363039602
      proportion: 0.0076
    2:
      count: 827
      max: 0.04343757180112549
      mean: 0.0373
      min: 0.03143614639713355
      proportion: 0.011
    3:
      count: 827
      max: 0.05720957632443194
      mean: 0.0502
      min: 0.04343757180112549
      proportion: 0.0152
    4:
      count: 826
      max: 0.07506400777461679
      mean: 0.0658
      min: 0.05720957632443194
      proportion: 0.024
    5:
      count: 826
      max: 0.09676393939753763
      mean: 0.0854
      min: 0.07506400777461679
      proportion: 0.0359
    6:
      count: 826
      max: 0.12623625947343917
      mean: 0.1112
      min: 0.09676393939753763
      proportion: 0.0526
    7:
      count: 826
      max: 0.17054510746110527
      mean: 0.1468
      min: 0.12623625947343917
      proportion: 0.0821
    8:
      count: 826
      max: 0.2500177749241296
      mean: 0.2048
      min: 0.17054510746110527
      proportion: 0.1411
    9:
      count: 826
      max: inf
      mean: 0.3673
      min: 0.2500177749241296
      proportion: 0.6254
  fea_handset_count_05m:
    0:
      max: 1.5
      min: -inf
      proportion: 0.5817
    1:
      max: 2.5
      min: 1.5
      proportion: 0.2584
    2:
      max: 3.5
      min: 2.5
      proportion: 0.0972
    3:
      max: 4.5
      min: 3.5
      proportion: 0.0357
    4:
      max: inf
      min: 4.5
      proportion: 0.027
  fea_int_app_usage_credit_lending_company_accessed_apps_03m:
    0:
      max: 0.5
      min: -inf
      proportion: 0.9691
    1:
      max: 1.5
      min: 0.5
      proportion: 0.0245
    2:
      max: 3.5
      min: 1.5
      proportion: 0.0045
    3:
      max: inf
      min: 3.5
      proportion: 0.0019
  fea_int_app_usage_credit_lending_company_data_vol_03m:
    0:
      max: 522166.5
      min: -inf
      proportion: 0.9822
    1:
      max: 1354203.0
      min: 522166.5
      proportion: 0.0049
    2:
      max: 9004698.0
      min: 1354203.0
      proportion: 0.0089
    3:
      max: 32201226.0
      min: 9004698.0
      proportion: 0.0029
    4:
      max: inf
      min: 32201226.0
      proportion: 0.0012
  fea_int_app_usage_ecommerce_data_vol_03m:
    0:
      max: 67641904.0
      min: -inf
      proportion: 0.9086
    1:
      max: 209714792.0
      min: 67641904.0
      proportion: 0.0405
    2:
      max: 428595600.0
      min: 209714792.0
      proportion: 0.0204
    3:
      max: 1070993088.0
      min: 428595600.0
      proportion: 0.0183
    4:
      max: inf
      min: 1070993088.0
      proportion: 0.0121
  fea_int_app_usage_facebook_data_vol_03m:
    0:
      max: 111205752.0
      min: -inf
      proportion: 0.6498
    1:
      max: 736525504.0
      min: 111205752.0
      proportion: 0.1257
    2:
      max: 4192387712.0
      min: 736525504.0
      proportion: 0.1439
    3:
      max: 8955256320.0
      min: 4192387712.0
      proportion: 0.0429
    4:
      max: inf
      min: 8955256320.0
      proportion: 0.0376
  fea_int_app_usage_gambling_data_vol_03m:
    0:
      max: 552.0
      min: -inf
      proportion: 0.8644
    1:
      max: 188092.0
      min: 552.0
      proportion: 0.0733
    2:
      max: 1527153.0
      min: 188092.0
      proportion: 0.0389
    3:
      max: 5977604.0
      min: 1527153.0
      proportion: 0.0123
    4:
      max: inf
      min: 5977604.0
      proportion: 0.0111
  fea_int_app_usage_mobile_wallets_data_vol_03m:
    0:
      max: 22718.5
      min: -inf
      proportion: 0.8359
    1:
      max: 399201.0
      min: 22718.5
      proportion: 0.0858
    2:
      max: 3453707.0
      min: 399201.0
      proportion: 0.0441
    3:
      max: 38728600.0
      min: 3453707.0
      proportion: 0.0272
    4:
      max: inf
      min: 38728600.0
      proportion: 0.0069
  fea_int_usage_non_zero_usage_days_03m:
    0:
      max: 4.5
      min: -inf
      proportion: 0.4936
    1:
      max: 51.5
      min: 4.5
      proportion: 0.2261
    2:
      max: 86.5
      min: 51.5
      proportion: 0.1165
    3:
      max: 90.5
      min: 86.5
      proportion: 0.0464
    4:
      max: inf
      min: 90.5
      proportion: 0.1174
  fea_los:
    0:
      max: 173.5
      min: -inf
      proportion: 0.2849
    1:
      max: 311.5
      min: 173.5
      proportion: 0.1142
    2:
      max: 512.5
      min: 311.5
      proportion: 0.0954
    3:
      max: 1376.5
      min: 512.5
      proportion: 0.2176
    4:
      max: inf
      min: 1376.5
      proportion: 0.2878
  fea_rech_tot_amt_avg_03m:
    0:
      max: 24934.4091796875
      min: -inf
      proportion: 0.7195
    1:
      max: 43101.724609375
      min: 24934.4091796875
      proportion: 0.1223
    2:
      max: 64942.30859375
      min: 43101.724609375
      proportion: 0.0799
    3:
      max: 77738.63671875
      min: 64942.30859375
      proportion: 0.0282
    4:
      max: inf
      min: 77738.63671875
      proportion: 0.05
  fea_rech_tot_trx_sum_03m:
    0:
      max: 0.5
      min: -inf
      proportion: 0.2251
    1:
      max: 12.5
      min: 0.5
      proportion: 0.6787
    2:
      max: 18.5
      min: 12.5
      proportion: 0.051
    3:
      max: 25.5
      min: 18.5
      proportion: 0.0234
    4:
      max: inf
      min: 25.5
      proportion: 0.0218
  fea_rev_voice_tot_sum_03m:
    0:
      max: 152.5
      min: -inf
      proportion: 0.4403
    1:
      max: 1634.5
      min: 152.5
      proportion: 0.0391
    2:
      max: 3188.5
      min: 1634.5
      proportion: 0.0308
    3:
      max: 6072.5
      min: 3188.5
      proportion: 0.0511
    4:
      max: inf
      min: 6072.5
      proportion: 0.4386
  fea_txt_msg_banks_unique_senders_count_03m:
    0:
      max: 0.5
      min: -inf
      proportion: 0.9071
    1:
      max: 1.5
      min: 0.5
      proportion: 0.0611
    2:
      max: 2.5
      min: 1.5
      proportion: 0.0188
    3:
      max: inf
      min: 2.5
      proportion: 0.013
  fea_txt_msg_credit_lending_companies_incoming_count_03m:
    0:
      max: 1.5
      min: -inf
      proportion: 0.9786
    1:
      max: 3.5
      min: 1.5
      proportion: 0.0066
    2:
      max: 32.5
      min: 3.5
      proportion: 0.0114
    3:
      max: 55.5
      min: 32.5
      proportion: 0.0015
    4:
      max: inf
      min: 55.5
      proportion: 0.0019
  fea_txt_msg_credit_lending_companies_unique_senders_count_03m:
    0:
      max: 1.5
      min: -inf
      proportion: 0.9907
    1:
      max: 2.5
      min: 1.5
      proportion: 0.0042
    2:
      max: 4.5
      min: 2.5
      proportion: 0.0026
    3:
      max: 7.5
      min: 4.5
      proportion: 0.0013
    4:
      max: inf
      min: 7.5
      proportion: 0.0012
  fea_txt_msg_ecommerce_shopping_incoming_count_03m:
    0:
      max: 0.5
      min: -inf
      proportion: 0.8796
    1:
      max: 1.5
      min: 0.5
      proportion: 0.0513
    2:
      max: 6.5
      min: 1.5
      proportion: 0.0519
    3:
      max: 13.5
      min: 6.5
      proportion: 0.0109
    4:
      max: inf
      min: 13.5
      proportion: 0.0064
  fea_txt_msg_incoming_count_03m:
    0:
      max: 125.5
      min: -inf
      proportion: 0.4616
    1:
      max: 470.5
      min: 125.5
      proportion: 0.3901
    2:
      max: 687.5
      min: 470.5
      proportion: 0.0695
    3:
      max: 1099.5
      min: 687.5
      proportion: 0.0448
    4:
      max: inf
      min: 1099.5
      proportion: 0.034
  fea_voice_tot_dur_12_5_am_03m:
    0:
      max: 7.5
      min: -inf
      proportion: 0.3515
    1:
      max: 39.5
      min: 7.5
      proportion: 0.261
    2:
      max: 67.5
      min: 39.5
      proportion: 0.0811
    3:
      max: 122.5
      min: 67.5
      proportion: 0.0795
    4:
      max: inf
      min: 122.5
      proportion: 0.2269
  fea_voice_tot_uniq_inc_calls_03m:
    0:
      max: 2.5
      min: -inf
      proportion: 0.3992
    1:
      max: 21.5
      min: 2.5
      proportion: 0.3517
    2:
      max: 48.5
      min: 21.5
      proportion: 0.1574
    3:
      max: 89.5
      min: 48.5
      proportion: 0.0641
    4:
      max: inf
      min: 89.5
      proportion: 0.0277
  fea_voice_tot_uniq_out_calls_03m:
    0:
      max: 0.5
      min: -inf
      proportion: 0.3326
    1:
      max: 2.5
      min: 0.5
      proportion: 0.0953
    2:
      max: 10.5
      min: 2.5
      proportion: 0.2072
    3:
      max: 70.5
      min: 10.5
      proportion: 0.3099
    4:
      max: inf
      min: 70.5
      proportion: 0.055

columns_to_include:
  - "weekstart"
  - "dimension"
  - "bins"
  - "proportion_baseline"
  - "proportion_current"
  - "psi"
