pipeline: training
hdfs_base_path: hdfs:///data/landing/gx_pnt/ # HDFS Base Path
filter_partner_data: True

# if neither "first_weekstart" nor "last_weekstart" are specified, then the pipeline will run for weekstarts = last week (last Monday) only
# if only "first_weekstart" is specified then the pipeline will run for weekstarts between first_weekstart and last week (last Monday)
# if only "last_weekstart" is specified then the pipeline will run for weekstart which = last_weekstart only
# if both "first_weekstart" & "last_weekstart" are specified then the pipeline will run for weekstarts between first_weekstart and last_weekstart

first_weekstart: 2019-11-25 # should be a monday
# last_weekstart: 2020-03-16 # should be a monday

# first_month: 2020-01-01
# last_month: 2020-01-31

sla_date: 8 #parameter for mobility features sla

pii_level_columns:
    - msisdn
    - anumber
    - bnumber

# Configurations to Send email for timeliness check & msisnd delta check
send_all: false # set to false if only need to send errors
email_notif_enabled: false
email_notif_setup:
  smtp_relay_host: "10.2.126.85"
  smtp_relay_port: 25
  from_email: "cdsw@telkomsel.co.id"
  to_emails:
    - "arianto@telkomsel.co.id"

# Covid-19 parameters
pre_covid_first_weekstart: 2020-01-06
pre_covid_last_weekstart: 2020-02-24
covid_first_weekstart: 2020-03-09
covid_last_weekstart: 2020-06-01
post_covid_first_weekstart: 2020-06-08
post_covid_last_weekstart: 2020-08-31
