#####################################################################################################################################
############################################## 4G Stimulation ##############################################################
#####################################################################################################################################
4g_lte_map_cols:
  - msisdn
  - segment
  - device4g
  - usim
  - sdn
  - payload_4g_kb

4g_cb_prepaid_postpaid_cols:
  - msisdn
  - lac
  - ci
 
4g_imeidb_cols:
  - msisdn
  - imei
  - tac
  - manufacture
  - design_type
  - device_type
  - data_capable
  - os
  - network
  - multisim
  - volte

4g_downsample_fraction: .1
4g_segment: SEGMENT_2
4g_weekstart: 2020-06-15
4g_path_to_save_hist: /home/cdsw/project_mck_dmp/data/4g/03_train_table/histogram_202001.pdf
4g_path_to_save_corr_matrix_plot: /home/cdsw/project_mck_dmp/data/4g/03_train_table/corr_matrix_202001.pdf

4g_x_axis_scatter: 0
4g_y_axis_scatter: 1
4g_path_to_save_scatter: /home/cdsw/project_mck_dmp/data/4g/03_train_table/cluster_plot_202001.pdf

4g_clustering_unit_of_analysis:
    - lac_ci
    - weekstart
    - msisdn

4g_clustering_features_to_select:
    - lac_ci
    - weekstart
    - msisdn
    - fea_custprof_segment_data_user
    - fea_los
    - fea_custprof_status
    - fea_custprof_brand
    - fea_custprof_segment_hvc_mtd
    - fea_custprof_segment_hvc_m1
    - fea_custprof_loyalty_tier
    - fea_custprof_nik_age
    - fea_custprof_arpu_segment_name
    - fea_handset_imeis
    - fea_handset_count_01m
    - fea_handset_count_02m
    - fea_handset_count_03m
    - fea_handset_count_04m
    - fea_handset_count_05m
    - fea_handset_changed_count_01m
    - fea_handset_changed_count_02m
    - fea_handset_changed_count_03m
    - fea_handset_changed_count_04m
    - fea_handset_changed_count_05m
    - fea_int_app_usage_onlinebanking_data_vol_01w
    - fea_int_app_usage_onlinebanking_data_vol_02w
    - fea_int_app_usage_onlinebanking_data_vol_03w
    - fea_int_app_usage_onlinebanking_data_vol_01m
    - fea_int_app_usage_onlinebanking_data_vol_02m
    - fea_int_app_usage_onlinebanking_data_vol_03m
    - fea_int_app_usage_onlinebanking_accessed_apps_01w
    - fea_int_app_usage_onlinebanking_accessed_apps_02w
    - fea_int_app_usage_onlinebanking_accessed_apps_03w
    - fea_int_app_usage_onlinebanking_accessed_apps_01m
    - fea_int_app_usage_onlinebanking_accessed_apps_02m
    - fea_int_app_usage_onlinebanking_accessed_apps_03m
    - fea_int_app_usage_education_data_vol_01w
    - fea_int_app_usage_education_data_vol_02w
    - fea_int_app_usage_education_data_vol_03w
    - fea_int_app_usage_education_data_vol_01m
    - fea_int_app_usage_education_data_vol_02m
    - fea_int_app_usage_education_data_vol_03m
    - fea_int_app_usage_education_accessed_apps_01w
    - fea_int_app_usage_education_accessed_apps_02w
    - fea_int_app_usage_education_accessed_apps_03w
    - fea_int_app_usage_education_accessed_apps_01m
    - fea_int_app_usage_education_accessed_apps_02m
    - fea_int_app_usage_education_accessed_apps_03m
    - fea_int_app_usage_gaming_data_vol_01w
    - fea_int_app_usage_gaming_data_vol_02w
    - fea_int_app_usage_gaming_data_vol_03w
    - fea_int_app_usage_gaming_data_vol_01m
    - fea_int_app_usage_gaming_data_vol_02m
    - fea_int_app_usage_gaming_data_vol_03m
    - fea_int_app_usage_gaming_accessed_apps_01w
    - fea_int_app_usage_gaming_accessed_apps_02w
    - fea_int_app_usage_gaming_accessed_apps_03w
    - fea_int_app_usage_gaming_accessed_apps_01m
    - fea_int_app_usage_gaming_accessed_apps_02m
    - fea_int_app_usage_gaming_accessed_apps_03m
    - fea_int_app_usage_finance_sites_data_vol_01w
    - fea_int_app_usage_finance_sites_data_vol_02w
    - fea_int_app_usage_finance_sites_data_vol_03w
    - fea_int_app_usage_finance_sites_data_vol_01m
    - fea_int_app_usage_finance_sites_data_vol_02m
    - fea_int_app_usage_finance_sites_data_vol_03m
    - fea_int_app_usage_finance_sites_accessed_apps_01w
    - fea_int_app_usage_finance_sites_accessed_apps_02w
    - fea_int_app_usage_finance_sites_accessed_apps_03w
    - fea_int_app_usage_finance_sites_accessed_apps_01m
    - fea_int_app_usage_finance_sites_accessed_apps_02m
    - fea_int_app_usage_finance_sites_accessed_apps_03m
    - fea_int_app_usage_social_media_sites_data_vol_01w
    - fea_int_app_usage_social_media_sites_data_vol_02w
    - fea_int_app_usage_social_media_sites_data_vol_03w
    - fea_int_app_usage_social_media_sites_data_vol_01m
    - fea_int_app_usage_social_media_sites_data_vol_02m
    - fea_int_app_usage_social_media_sites_data_vol_03m
    - fea_int_app_usage_social_media_sites_accessed_apps_01w
    - fea_int_app_usage_social_media_sites_accessed_apps_02w
    - fea_int_app_usage_social_media_sites_accessed_apps_03w
    - fea_int_app_usage_social_media_sites_accessed_apps_01m
    - fea_int_app_usage_social_media_sites_accessed_apps_02m
    - fea_int_app_usage_social_media_sites_accessed_apps_03m
    - fea_int_app_usage_social_media_sites_days_since_first_usage
    - fea_int_app_usage_social_media_sites_days_since_last_usage
    - fea_int_app_usage_payments_data_vol_01w
    - fea_int_app_usage_payments_data_vol_02w
    - fea_int_app_usage_payments_data_vol_03w
    - fea_int_app_usage_payments_data_vol_01m
    - fea_int_app_usage_payments_data_vol_02m
    - fea_int_app_usage_payments_data_vol_03m
    - fea_int_app_usage_payments_accessed_apps_01w
    - fea_int_app_usage_payments_accessed_apps_02w
    - fea_int_app_usage_payments_accessed_apps_03w
    - fea_int_app_usage_payments_accessed_apps_01m
    - fea_int_app_usage_payments_accessed_apps_02m
    - fea_int_app_usage_payments_accessed_apps_03m
    - fea_int_usage_non_zero_usage_days_03m
    - fea_int_usage_zero_usage_count_to_usage_count_ratio_03m
    - fea_int_usage_tot_kb_data_usage_03m
    - fea_int_usage_daily_avg_kb_data_usage_03m
    - fea_int_usage_2g_kb_data_usage_03m
    - fea_int_usage_3g_kb_data_usage_03m
    - fea_int_usage_4g_kb_data_usage_03m
    - fea_int_usage_4g_kb_data_usage_01m
    - fea_int_usage_weekday_kb_usage_03m
    - fea_int_usage_weekend_kb_usage_03m
    - fea_rech_tot_amt_sum_02m
    - fea_rech_tot_amt_sum_03m
    - fea_rech_tot_trx_sum_02m
    - fea_rech_tot_trx_sum_03m
    - fea_rech_tot_amt_avg_02m
    - fea_rech_tot_amt_avg_03m
    - fea_rech_tot_amt_stddev_03m
    - fea_rech_tot_days_no_bal_sum_01w
    - fea_rech_tot_days_no_bal_sum_02w
    - fea_rech_tot_days_no_bal_sum_03w
    - fea_rech_tot_days_no_bal_sum_01m
    - fea_rech_tot_days_no_bal_sum_02m
    - fea_rech_tot_days_no_bal_sum_03m
    - fea_rech_tot_days_no_bal_avg_03m
    - fea_rech_tot_days_no_bal_avg_02m
    - fea_rech_annualize_factor
    - fea_rev_voice_tot_sum_01m
    - fea_rev_voice_tot_sum_02m
    - fea_rev_voice_tot_sum_03m
    - fea_rev_data_tot_sum_01m
    - fea_rev_data_tot_sum_02m
    - fea_rev_data_tot_sum_03m
    - fea_rev_sms_tot_sum_01m
    - fea_rev_sms_tot_sum_02m
    - fea_rev_sms_tot_sum_03m
    - fea_rev_data_sms_tot_sum_01m
    - fea_rev_data_sms_tot_sum_02m
    - fea_rev_data_sms_tot_sum_03m
    - fea_rev_voice_weekend_tot_sum_03m
    - fea_rev_data_weekend_tot_sum_03m
    - fea_rev_sms_weekend_tot_sum_03m
    - fea_rev_data_sms_weekend_tot_sum_03m
    - fea_rev_voice_sms_weekend_tot_sum_03m
    - fea_rev_voice_data_weekend_tot_sum_03m
    - segment
    - device4g
    - usim
    - sdn
    - payload_4g_kb
    - manufacture
    - device_type
    - data_capable
    - os
    - network
    - multisim
    - volte
    - fea_network_broadband_revenue_avg_6m
    - fea_network_ccsr_cs_avg_6m
    - fea_network_ccsr_ps_avg_6m
    - fea_network_cssr_cs_avg_6m
    - fea_network_cssr_ps_avg_6m
    - fea_network_downlink_traffic_volume_mb_avg_6m
    - fea_network_edge_mbyte_avg_6m
    - fea_network_gprs_mbyte_avg_6m
    - fea_network_hosr_num_sum_avg_6m
    - fea_network_hsdpa_accesability_avg_6m
    - fea_network_hsupa_accesability_avg_6m
    - fea_network_hsupa_mean_user_avg_6m
    - fea_network_ifhosr_avg_6m
    - fea_network_payload_hspa_mbyte_avg_6m
    - fea_network_payload_psr99_mbyte_avg_6m
    - fea_network_total_payload_mb_avg_6m
    - fea_network_total_throughput_kbps_avg_6m
    - fea_network_voice_revenue_avg_6m
    - fea_network_volume_voice_traffic_erl_avg_6m
    - fea_network_hosr_avg_6m
    - fea_network_hosr_denum_sum_avg_6m

4g_clustering_cols_to_log:
    - fea_handset_imeis
    - fea_handset_count_01m
    - fea_handset_count_02m
    - fea_handset_count_03m
    - fea_handset_count_04m
    - fea_handset_count_05m
    - fea_handset_changed_count_01m
    - fea_handset_changed_count_02m
    - fea_handset_changed_count_03m
    - fea_handset_changed_count_04m
    - fea_handset_changed_count_05m
    - fea_rev_voice_tot_sum_01m
    - fea_rev_voice_tot_sum_02m
    - fea_rev_voice_tot_sum_03m
    - fea_rev_data_tot_sum_01m
    - fea_rev_data_tot_sum_02m
    - fea_rev_data_tot_sum_03m
    - fea_rev_sms_tot_sum_01m
    - fea_rev_sms_tot_sum_02m
    - fea_rev_sms_tot_sum_03m
    - fea_rev_data_sms_tot_sum_01m
    - fea_rev_data_sms_tot_sum_02m
    - fea_rev_data_sms_tot_sum_03m
    - fea_rev_voice_weekend_tot_sum_03m
    - fea_rev_data_weekend_tot_sum_03m
    - fea_rev_sms_weekend_tot_sum_03m
    - fea_rev_data_sms_weekend_tot_sum_03m
    - fea_rev_voice_sms_weekend_tot_sum_03m
    - fea_rev_voice_data_weekend_tot_sum_03m

4g_clustering_imputation_method: zero
4g_clustering_limit_manuf: 10

4G_dimension_reduction_parameter:
    n_components_reduction: 10
    n_iter_reduction: 3
    copy_reduction: True
    check_input_reduction: True
    engine_reduction: 'auto'
    random_state_reduction: 42

4G_clustering_parameter:
    n_clusters: 20
    n_init_clusters: 30
    max_iter_clusters: 1500
    n_jobs_clusters: -1
    random_state_clustering: 42

4g_score_or_train_tag: train
4g_sample_size_to_compute_stats: 200000
#####################################################################################################################################
############################################## ses Stimulation ##############################################################
#####################################################################################################################################
ses_downsample_fraction: .1
ses_weekstart: 2020-06-15
ses_segment_low: low
ses_segment_medium: medium
ses_segment_high: high
agg_cols_to_select:
    - msisdn
    - trx_pkg_prchse
    - rev_pkg_prchse
    - trx_voice_pkg_prchs
    - trx_sms_pkg_prchs
    - trx_data_pkg_prchs
    - trx_roam_pkg_prchs
    - rev_voice_pkg_prchs
    - rev_sms_pkg_prchs
    - rev_data_pkg_prchs
    - rev_roam_pkg_prchs

ses_cols_to_select:
    - msisdn
    - fea_handset_count_01m
    - fea_handset_count_02m
    - fea_handset_count_03m
    - fea_handset_changed_count_01m
    - fea_handset_changed_count_02m
    - fea_handset_changed_count_03m
    - fea_int_app_usage_onlinebanking_data_vol_01m
    - fea_int_app_usage_onlinebanking_data_vol_02m
    - fea_int_app_usage_onlinebanking_data_vol_03m
    - fea_int_app_usage_onlinebanking_accessed_apps_01m
    - fea_int_app_usage_onlinebanking_accessed_apps_02m
    - fea_int_app_usage_onlinebanking_accessed_apps_03m
    - fea_int_app_usage_education_accessed_apps_01m
    - fea_int_app_usage_education_accessed_apps_02m
    - fea_int_app_usage_education_accessed_apps_03m
    - fea_int_app_usage_gaming_data_vol_01m
    - fea_int_app_usage_gaming_data_vol_02m
    - fea_int_app_usage_gaming_data_vol_03m
    - fea_int_app_usage_gaming_accessed_apps_01m
    - fea_int_app_usage_gaming_accessed_apps_02m
    - fea_int_app_usage_gaming_accessed_apps_03m
    - fea_int_app_usage_social_media_sites_data_vol_01m
    - fea_int_app_usage_social_media_sites_data_vol_02m
    - fea_int_app_usage_social_media_sites_data_vol_03m
    - fea_int_app_usage_social_media_sites_accessed_apps_01m
    - fea_int_app_usage_social_media_sites_accessed_apps_02m
    - fea_int_app_usage_social_media_sites_accessed_apps_03m
    - fea_int_app_usage_payments_data_vol_01m
    - fea_int_app_usage_payments_data_vol_02m
    - fea_int_app_usage_payments_data_vol_03m
    - fea_int_app_usage_payments_accessed_apps_01m
    - fea_int_app_usage_payments_accessed_apps_02m
    - fea_int_app_usage_payments_accessed_apps_03m
    - fea_int_usage_zero_usage_days_03m
    - fea_int_usage_non_zero_usage_days_03m
    - fea_int_usage_tot_kb_data_usage_01m
    - fea_int_usage_tot_kb_data_usage_02m
    - fea_int_usage_tot_kb_data_usage_03m
    - fea_int_usage_2g_kb_data_usage_01m
    - fea_int_usage_2g_kb_data_usage_02m
    - fea_int_usage_2g_kb_data_usage_03m
    - fea_int_usage_3g_kb_data_usage_01m
    - fea_int_usage_3g_kb_data_usage_02m
    - fea_int_usage_3g_kb_data_usage_03m
    - fea_int_usage_4g_kb_data_usage_01m
    - fea_int_usage_4g_kb_data_usage_02m
    - fea_int_usage_4g_kb_data_usage_03m
    - fea_int_usage_weekday_kb_usage_01m
    - fea_int_usage_weekend_kb_usage_01m
    - fea_int_usage_weekday_kb_usage_02m
    - fea_int_usage_weekend_kb_usage_02m
    - fea_int_usage_weekday_kb_usage_03m
    - fea_int_usage_weekend_kb_usage_03m
    - fea_rech_tot_amt_sum_01m
    - fea_rech_tot_amt_sum_02m
    - fea_rech_tot_amt_sum_03m
    - fea_rech_tot_trx_sum_01m
    - fea_rech_tot_trx_sum_02m
    - fea_rech_tot_trx_sum_03m
    - fea_rech_tot_amt_avg_02m
    - fea_rech_tot_amt_avg_03m
    - fea_rech_tot_trx_trd_03m
    - fea_rech_tot_amt_stddev_03m
    - trx_pkg_prchse
    - rev_pkg_prchse
    - trx_voice_pkg_prchs
    - trx_sms_pkg_prchs
    - trx_data_pkg_prchs
    - trx_roam_pkg_prchs
    - rev_voice_pkg_prchs
    - rev_sms_pkg_prchs
    - rev_data_pkg_prchs
    - rev_roam_pkg_prchs
    - fea_rech_trx_pkg_prchse_sum_01m
    - fea_rech_trx_pkg_prchse_sum_02m
    - fea_rech_trx_pkg_prchse_sum_03m
    - fea_rech_trx_pkg_prchse_avg_03m
    - fea_rech_trx_pkg_prchse_avg_02m
    - fea_rech_rev_pkg_prchse_sum_01m
    - fea_rech_rev_pkg_prchse_sum_02m
    - fea_rech_rev_pkg_prchse_sum_03m
    - fea_rech_rev_pkg_prchse_avg_03m
    - fea_rech_rev_pkg_prchse_avg_02m
    - fea_rech_tot_days_no_bal_sum_01m
    - fea_rech_tot_days_no_bal_sum_02m
    - fea_rech_tot_days_no_bal_sum_03m
    - fea_rech_tot_days_no_bal_avg_03m
    - fea_rech_tot_days_no_bal_avg_02m
    - fea_rev_voice_tot_sum_01m
    - fea_rev_voice_tot_sum_02m
    - fea_rev_voice_tot_sum_03m
    - fea_rev_data_tot_sum_01m
    - fea_rev_data_tot_sum_02m
    - fea_rev_data_tot_sum_03m
    - fea_rev_sms_tot_sum_01m
    - fea_rev_sms_tot_sum_02m
    - fea_rev_sms_tot_sum_03m
    - fea_rev_data_sms_tot_sum_01m
    - fea_rev_data_sms_tot_sum_02m
    - fea_rev_data_sms_tot_sum_03m
    - fea_rev_voice_weekend_tot_sum_01m
    - fea_rev_voice_weekend_tot_sum_02m
    - fea_rev_voice_weekend_tot_sum_03m
    - fea_rev_data_weekend_tot_sum_01m
    - fea_rev_data_weekend_tot_sum_02m
    - fea_rev_data_weekend_tot_sum_03m
    - fea_rev_sms_weekend_tot_sum_01m
    - fea_rev_sms_weekend_tot_sum_02m
    - fea_rev_sms_weekend_tot_sum_03m
    - fea_rev_data_sms_weekend_tot_sum_01m
    - fea_rev_data_sms_weekend_tot_sum_02m
    - fea_rev_data_sms_weekend_tot_sum_03m
    - fea_rev_voice_sms_weekend_tot_sum_01m
    - fea_rev_voice_sms_weekend_tot_sum_02m
    - fea_rev_voice_sms_weekend_tot_sum_03m
    - fea_rev_voice_data_weekend_tot_sum_01m
    - fea_rev_voice_data_weekend_tot_sum_02m
    - fea_rev_voice_data_weekend_tot_sum_03m
    - fea_txt_msg_incoming_count_01m
    - fea_txt_msg_incoming_count_02m
    - fea_txt_msg_incoming_count_03m
    - fea_txt_msg_outgoing_count_01m
    - fea_txt_msg_outgoing_count_02m
    - fea_txt_msg_outgoing_count_03m
    - fea_txt_msg_count_01m
    - fea_txt_msg_count_02m
    - fea_txt_msg_count_03m
    - fea_txt_msg_voice_ratio_01m
    - fea_txt_msg_voice_ratio_02m
    - fea_txt_msg_voice_ratio_incoming_01m
    - fea_txt_msg_voice_ratio_incoming_02m
    - fea_txt_msg_voice_ratio_incoming_03m
    - fea_txt_msg_voice_ratio_outgoing_01m
    - fea_txt_msg_voice_ratio_outgoing_02m
    - fea_txt_msg_voice_ratio_outgoing_03m
    - fea_txt_msg_banks_incoming_count_03m
    - fea_txt_msg_credit_lending_companies_incoming_count_03m
    - fea_txt_msg_ecommerce_shopping_incoming_count_03m
    - fea_txt_msg_mobile_wallets_incoming_count_03m
    - fea_txt_msg_other_online_services_incoming_count_02m
    - fea_txt_msg_multifinance_incoming_count_02m
    - fea_txt_msg_banks_unique_senders_count_03m
    - fea_txt_msg_credit_lending_companies_unique_senders_count_03m
    - fea_txt_msg_travel_company_unique_senders_count_02m
    - fea_voice_inc_call_dur_01m
    - fea_voice_inc_call_dur_02m
    - fea_voice_inc_call_dur_03m
    - fea_voice_out_call_dur_01m
    - fea_voice_out_call_dur_02m
    - fea_voice_out_call_dur_03m
    - fea_voice_tot_call_dur_01m
    - fea_voice_tot_call_dur_02m
    - fea_voice_tot_call_dur_03m
    - fea_voice_tot_inc_calls_01m
    - fea_voice_tot_inc_calls_02m
    - fea_voice_tot_inc_calls_03m
    - fea_voice_tot_out_calls_01m
    - fea_voice_tot_out_calls_02m
    - fea_voice_tot_out_calls_03m
    - fea_voice_tot_calls_01m
    - fea_voice_tot_calls_02m
    - fea_voice_tot_calls_03m
    - fea_voice_inc_to_tot_calls_num_03m
    - fea_voice_inc_to_tot_calls_dur_03m
    - fea_voice_tot_uniq_inc_calls_01m
    - fea_voice_tot_uniq_inc_calls_02m
    - fea_voice_tot_uniq_inc_calls_03m
    - fea_voice_tot_uniq_out_calls_01m
    - fea_voice_tot_uniq_out_calls_02m
    - fea_voice_tot_uniq_out_calls_03m
    - fea_voice_tot_uniq_calls_01m
    - fea_voice_tot_uniq_calls_02m
    - fea_voice_tot_uniq_calls_03m
    - fea_voice_avg_uniq_inc_call_03m
    - fea_voice_avg_uniq_out_call_03m
    - fea_voice_avg_uniq_tot_call_03m
    - fea_voice_tot_dur_12_5_am_03m
    - fea_custprof_segment_data_user
    - fea_los
    - fea_custprof_status
    - fea_custprof_brand
    - fea_custprof_segment_hvc_mtd
    - fea_custprof_segment_hvc_m1
    - fea_custprof_loyalty_tier
    - fea_custprof_nik_age
    - fea_custprof_arpu_segment_name
    
ses_cols_to_select_log:
    - fea_handset_count_01m
    - fea_handset_count_02m
    - fea_handset_count_03m
    - fea_handset_changed_count_01m
    - fea_handset_changed_count_02m
    - fea_handset_changed_count_03m
    - fea_rev_voice_tot_sum_01m
    - fea_rev_voice_tot_sum_02m
    - fea_rev_voice_tot_sum_03m
    - fea_rev_data_tot_sum_01m
    - fea_rev_data_tot_sum_02m
    - fea_rev_data_tot_sum_03m
    - fea_rev_sms_tot_sum_01m
    - fea_rev_sms_tot_sum_02m
    - fea_rev_sms_tot_sum_03m
    - fea_rev_data_sms_tot_sum_01m
    - fea_rev_data_sms_tot_sum_02m
    - fea_rev_data_sms_tot_sum_03m
    - fea_rev_voice_weekend_tot_sum_03m
    - fea_rev_data_weekend_tot_sum_03m
    - fea_rev_sms_weekend_tot_sum_03m
    - fea_rev_data_sms_weekend_tot_sum_03m
    - fea_rev_voice_sms_weekend_tot_sum_03m
    - fea_rev_voice_data_weekend_tot_sum_03m

ses_cols_to_drop:
    - fea_rech_tot_amt_sum_01m
    - fea_rech_tot_amt_sum_02m
    - fea_rech_tot_amt_sum_03m
    - fea_rech_tot_amt_avg_02m
    - fea_rech_tot_amt_avg_03m
