pai_experiment: "Kredivo"
pai_run_name: "Kredivo Default Probability"

features_used:
    - "fea_txt_msg_incoming_count_03m"
    - "fea_txt_msg_credit_lending_companies_unique_senders_count_03m"
    - "fea_los"
    - "fea_int_app_usage_ecommerce_data_vol_03m"
    - "fea_voice_tot_dur_12_5_am_03m"
    - "fea_txt_msg_ecommerce_shopping_incoming_count_03m"
    - "fea_handset_count_05m"
    - "fea_int_app_usage_credit_lending_company_days_since_last_usage"
    - "fea_txt_msg_banks_unique_senders_count_03m"
    - "fea_int_app_usage_transportation_and_logistics_data_vol_03m"
    - "fea_int_app_usage_gambling_data_vol_03m"
    - "fea_txt_msg_credit_lending_companies_incoming_count_03m"
    - "fea_int_app_usage_credit_lending_company_accessed_apps_03m"
    - "fea_rech_tot_days_no_bal_avg_03m"
    - "fea_rech_tot_amt_avg_03m"
    - "fea_int_app_usage_facebook_data_vol_03m"
    - "fea_int_usage_non_zero_usage_days_03m"
    - "fea_rech_tot_trx_sum_03m"
    - "fea_rev_voice_tot_sum_03m"
    - "fea_int_app_usage_mobile_wallets_accessed_apps_03m"
    
categorical_features: []
    
weeks_train: 12
weeks_test: 4
weeks_gap: 0

classifier_params:
    name: "catboost"
    params:
        iterations: 500
        l2_leaf_reg: 100
        depth: 6
        rsm: 0.5
        learning_rate: 0.05
        loss_function: "Logloss"
        verbose: False

common_query: "application_group == 'basic'"
train_query: "flag_bad_61 in [0, 1]"
test_query: "flag_bad_61 in [0, 1]"

train_target_expression_map:
    0: "flag_bad_61 == 0"
    1: "flag_bad_61 == 1"
test_target_expression_map:
    0: "flag_bad_61 == 0"
    1: "flag_bad_61 == 1"

reliability_diagrams_num_bins: 20

# gini.adjustment_type can be
#       'raw_proba' (raw probability)
#       'woe' (use of woe of bins instead of raw probability)
#       'avg_raw_proba' (use of average probability of bins instead of raw probability)
# gini.bin_type can be
#       'quantile'
#       'equal_size'
gini_params:
    adjustment_type: "raw_proba"
    bin_type: "quantile"
    num_bins: 20

extract_shap_values: True
log_train_data: True

# Do not modify parameters below, except for username at setup
use_spark: False
use_pai_logging: True

pai_username: "Adi"
pai_runs: "hdfs:///data/landing/gx_pnt/mck_dmp_ext/data_science/pai/klop_poc_wave2"

pai_tags:
    - "Default probability"

weekstart_column_name: "weekstart"
