from unittest import mock

from pyspark.sql import SparkSession
from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
)

from src.dmp.pipelines.dmp._04_features.mobility.nodes_covid.fea_covid_home_work_distance import (
    mobility_covid_home_work_distance,
)
from src.tests.pysaprk_df_equality import assert_df_frame_equal


class TestFeaCovidHomeWorkDistance:
    @mock.patch(
        "src.dmp.pipelines.dmp._04_features.mobility.nodes_covid.fea_covid_home_work_distance.calc_distance_bw_2_lat_long",
    )
    def test_fea_covid_home_work_distance(
        self, mock_calc_distance_bw_2_lat_long, spark_session: SparkSession
    ):
        mock_calc_distance_bw_2_lat_long.return_value = spark_session.createDataFrame(
            data=[
                [
                    "imsi_1",
                    "2020-01",
                    "qqu5d",
                    -6.38925,
                    106.98825,
                    "2000-01-20",
                    "qqd5e",
                    -6.389,
                    106.985,
                    "2000-01-20",
                    "2000-01-20",
                    360.2132372245001,
                ],
                [
                    "imsi_1",
                    "2020-02",
                    "qqu5d",
                    -6.38925,
                    106.98825,
                    "2000-01-21",
                    "qqd5e",
                    -6.389,
                    106.985,
                    "2000-01-21",
                    "2000-01-21",
                    360.2132372245001,
                ],
                [
                    "imsi_1",
                    "2020-03",
                    "qqu5d",
                    -6.38925,
                    106.98825,
                    "2000-01-22",
                    "qqd5e",
                    -6.389,
                    106.985,
                    "2000-01-22",
                    "2000-01-22",
                    360.2132372245001,
                ],
                [
                    "imsi_1",
                    "2020-04",
                    "qqu5d",
                    -6.38925,
                    106.98825,
                    "2000-01-23",
                    None,
                    None,
                    None,
                    None,
                    "2000-01-23",
                    None,
                ],
                [
                    "imsi_1",
                    "2020-05",
                    "qqu5d",
                    -6.38925,
                    106.98825,
                    "2000-01-24",
                    "qqd5e",
                    -6.389,
                    106.985,
                    "2000-01-24",
                    "2000-01-24",
                    360.2132372245001,
                ],
                [
                    "imsi_1",
                    "2020-06",
                    "qqu5d",
                    -6.38925,
                    106.98825,
                    "2000-01-24",
                    "qqd5e",
                    -6.389,
                    106.985,
                    "2000-01-24",
                    "2000-01-24",
                    360.2132372245001,
                ],
                [
                    "imsi_1",
                    "2020-07",
                    None,
                    None,
                    None,
                    None,
                    "qqd5e",
                    -6.389,
                    106.985,
                    "2000-01-26",
                    "2000-01-26",
                    None,
                ],
                [
                    "imsi_1",
                    "2020-08",
                    "qqu5d",
                    -6.38925,
                    106.98825,
                    "2000-01-27",
                    "qqd5e",
                    -6.389,
                    106.985,
                    "2000-01-27",
                    "2000-01-27",
                    360.2132372245001,
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("mo_id", StringType(), False),
                    StructField("home_geohash", StringType(), True),
                    StructField("lat1", DoubleType(), True),
                    StructField("long1", DoubleType(), True),
                    StructField("home_dt", StringType(), True),
                    StructField("work_geohash", StringType(), True),
                    StructField("lat2", DoubleType(), True),
                    StructField("long2", DoubleType(), True),
                    StructField("work_dt", StringType(), True),
                    StructField("month_mapped_dt", StringType(), True),
                    StructField("distance", DoubleType(), True),
                ]
            ),
        )

        home_agg_df = spark_session.createDataFrame(
            data=[
                [
                    "imsi_1",
                    "2020-01",
                    3380.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    3380.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-20",
                ],
                [
                    "imsi_1",
                    "2020-02",
                    3386.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    3386.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-21",
                ],
                [
                    "imsi_1",
                    "2020-03",
                    3860.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    3860.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-22",
                ],
                [
                    "imsi_1",
                    "2020-04",
                    3604.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    3604.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-23",
                ],
                [
                    "imsi_1",
                    "2020-05",
                    3360.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    3360.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-24",
                ],
                [
                    "imsi_1",
                    "2020-06",
                    3386.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    3386.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-25",
                ],
                [
                    "imsi_1",
                    "2020-07",
                    3386.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    3386.0,
                    1,
                    -6.38925,
                    106.98825,
                    0,
                    "2000-01-26",
                ],
                [
                    "imsi_1",
                    "2020-08",
                    3360.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    3360.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-27",
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("mo_id", StringType(), False),
                    StructField("home1_duration_max", DoubleType(), True),
                    StructField("geohash", StringType(), False),
                    StructField("home1_kelurahan_name", StringType(), True),
                    StructField("home1_neighboring_kelurahan_name", StringType(), True),
                    StructField("home1_kecamatan_name", StringType(), True),
                    StructField("home1_kabupaten_name", StringType(), True),
                    StructField("home1_province_name", StringType(), True),
                    StructField("home1_days", LongType(), True),
                    StructField("home1_duration", DoubleType(), True),
                    StructField("village_cnt", LongType(), True),
                    StructField("home1_lat", DoubleType(), True),
                    StructField("home1_lon", DoubleType(), True),
                    StructField("duration_max_flag", IntegerType(), False),
                    StructField("month_mapped_dt", StringType(), False),
                ]
            ),
        )

        work_agg_df = spark_session.createDataFrame(
            data=[
                [
                    "imsi_1",
                    "2020-01",
                    3380.0,
                    "qqd5e",
                    "kelurahan_2",
                    "neighbor_kelurahan_5",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.389,
                    106.985,
                    1,
                    "2000-01-20",
                ],
                [
                    "imsi_1",
                    "2020-02",
                    3386.0,
                    "qqd5e",
                    "kelurahan_2",
                    "neighbor_kelurahan_5",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.389,
                    106.985,
                    1,
                    "2000-01-21",
                ],
                [
                    "imsi_1",
                    "2020-03",
                    3860.0,
                    "qqd5e",
                    "kelurahan_2",
                    "neighbor_kelurahan_5",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.389,
                    106.985,
                    1,
                    "2000-01-22",
                ],
                [
                    "imsi_1",
                    "2020-04",
                    3604.0,
                    "qqd5e",
                    "kelurahan_2",
                    "neighbor_kelurahan_5",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.389,
                    106.985,
                    0,
                    "2000-01-23",
                ],
                [
                    "imsi_1",
                    "2020-05",
                    3360.0,
                    "qqd5e",
                    "kelurahan_2",
                    "neighbor_kelurahan_5",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.389,
                    106.985,
                    1,
                    "2000-01-24",
                ],
                [
                    "imsi_1",
                    "2020-06",
                    3386.0,
                    "qqd5e",
                    "kelurahan_2",
                    "neighbor_kelurahan_5",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.389,
                    106.985,
                    1,
                    "2000-01-25",
                ],
                [
                    "imsi_1",
                    "2020-07",
                    3386.0,
                    "qqd5e",
                    "kelurahan_2",
                    "neighbor_kelurahan_5",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.389,
                    106.985,
                    1,
                    "2000-01-26",
                ],
                [
                    "imsi_1",
                    "2020-08",
                    3360.0,
                    "qqd5e",
                    "kelurahan_2",
                    "neighbor_kelurahan_5",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.389,
                    106.985,
                    1,
                    "2000-01-27",
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("mo_id", StringType(), False),
                    StructField("work1_duration_max", DoubleType(), True),
                    StructField("geohash", StringType(), False),
                    StructField("work1_kelurahan_name", StringType(), True),
                    StructField("work1_neighboring_kelurahan_name", StringType(), True),
                    StructField("work1_kecamatan_name", StringType(), True),
                    StructField("work1_kabupaten_name", StringType(), True),
                    StructField("work1_province_name", StringType(), True),
                    StructField("work1_days", LongType(), True),
                    StructField("work1_duration", DoubleType(), True),
                    StructField("village_cnt", LongType(), True),
                    StructField("work1_lat", DoubleType(), True),
                    StructField("work1_lon", DoubleType(), True),
                    StructField("duration_max_flag", IntegerType(), False),
                    StructField("month_mapped_dt", StringType(), False),
                ]
            ),
        )

        actual_fea_df = mobility_covid_home_work_distance(home_agg_df, work_agg_df)

        expected_fea_df = spark_session.createDataFrame(
            data=[
                ["imsi_1", "2020-01", 360.2132372245001, None, None, None, None],
                ["imsi_1", "2020-02", 360.2132372245001, None, None, None, None],
                [
                    "imsi_1",
                    "2020-03",
                    360.2132372245001,
                    360.2132372245001,
                    None,
                    0.0,
                    None,
                ],
                [
                    "imsi_1",
                    "2020-04",
                    360.2132372245001,
                    360.2132372245001,
                    None,
                    0.0,
                    None,
                ],
                [
                    "imsi_1",
                    "2020-05",
                    360.2132372245001,
                    360.2132372245001,
                    None,
                    0.0,
                    None,
                ],
                [
                    "imsi_1",
                    "2020-06",
                    360.2132372245001,
                    360.2132372245001,
                    360.2132372245001,
                    0.0,
                    0.0,
                ],
                [
                    "imsi_1",
                    "2020-07",
                    360.2132372245001,
                    360.2132372245001,
                    None,
                    0.0,
                    None,
                ],
                [
                    "imsi_1",
                    "2020-08",
                    360.2132372245001,
                    360.2132372245001,
                    360.2132372245001,
                    0.0,
                    0.0,
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("mo_id", StringType(), False),
                    StructField(
                        "fea_mobility_pre_covid_avg_home_work_distance",
                        DoubleType(),
                        True,
                    ),
                    StructField(
                        "fea_mobility_covid_mar_apr_may_avg_home_work_distance",
                        DoubleType(),
                        True,
                    ),
                    StructField(
                        "fea_mobility_covid_jun_jul_aug_avg_home_work_distance",
                        DoubleType(),
                        True,
                    ),
                    StructField(
                        "fea_mobility_home_work_distance_diff_pre_post_covid_1",
                        DoubleType(),
                        True,
                    ),
                    StructField(
                        "fea_mobility_home_work_distance_diff_pre_post_covid_2",
                        DoubleType(),
                        True,
                    ),
                ]
            ),
        )

        assert_df_frame_equal(actual_fea_df, expected_fea_df)
