from unittest import mock

from pyspark.sql import SparkSession
from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
)

from src.dmp.pipelines.dmp._04_features.mobility.nodes.fea_work_poi import (
    mobility_work_poi_features,
)
from src.tests.pysaprk_df_equality import assert_df_frame_equal


class TestFeaWorkPoi:
    @mock.patch(
        "src.dmp.pipelines.dmp._04_features.mobility.nodes.fea_work_poi.calc_distance_bw_2_lat_long",
    )
    @mock.patch(
        "src.dmp.pipelines.dmp._04_features.mobility.nodes.fea_work_poi.neighbors",
        return_value=[
            ["qqu5e", "qqu5j", "qqu5k", "qqu6a", "qqu6b", "qqu6c", "qquc1", "qquc4"]
        ],
        autospec=True,
    )
    def test_fea_work_poi(
        self,
        mock_neighbors,
        mock_calc_distance_bw_2_lat_long,
        spark_session: SparkSession,
    ):
        mock_calc_distance_bw_2_lat_long.return_value = spark_session.createDataFrame(
            data=[
                [
                    "imsi_1",
                    "2020-03",
                    -6.38925,
                    106.98825,
                    24,
                    3860,
                    "qqu5d",
                    "commercial",
                    "commercial-store",
                    -6.3892,
                    106.9882,
                    "qqu57",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    750.586091493751,
                ],
                [
                    "imsi_1",
                    "2020-03",
                    -6.38925,
                    106.98825,
                    24,
                    3860,
                    "qqu5d",
                    "commercial",
                    "commercial",
                    -6.3892,
                    106.988,
                    "qqu5c",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    1150.86091493751,
                ],
                [
                    "imsi_1",
                    "2020-04",
                    -6.38925,
                    106.98825,
                    24,
                    3604,
                    "qqu5d",
                    "commercial",
                    "commercial-store",
                    -6.3892,
                    106.9882,
                    "qqu57",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    750.586091493751,
                ],
                [
                    "imsi_1",
                    "2020-04",
                    -6.38925,
                    106.98825,
                    24,
                    3604,
                    "qqu5d",
                    "commercial",
                    "commercial",
                    -6.3892,
                    106.988,
                    "qqu5c",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    1150.86091493751,
                ],
                [
                    "imsi_1",
                    "2020-05",
                    -6.38925,
                    106.98825,
                    24,
                    3360,
                    "qqu5d",
                    "commercial",
                    "commercial-store",
                    -6.3892,
                    106.9882,
                    "qqu57",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    750.586091493751,
                ],
                [
                    "imsi_1",
                    "2020-05",
                    -6.38925,
                    106.98825,
                    24,
                    3360,
                    "qqu5d",
                    "commercial",
                    "commercial",
                    -6.3892,
                    106.988,
                    "qqu5c",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    1150.86091493751,
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("mo_id", StringType(), False),
                    StructField("lat1", DoubleType(), True),
                    StructField("long1", DoubleType(), True),
                    StructField("work1_days", LongType(), True),
                    StructField("work1_duration", LongType(), True),
                    StructField("geohash", StringType(), True),
                    StructField("category_type_1", StringType(), True),
                    StructField("category_type_2", StringType(), True),
                    StructField("lat2", DoubleType(), True),
                    StructField("long2", DoubleType(), True),
                    StructField("poi_geohash", StringType(), True),
                    StructField("work1_kelurahan_name", StringType(), True),
                    StructField("work1_neighboring_kelurahan_name", StringType(), True),
                    StructField("work1_kecamatan_name", StringType(), True),
                    StructField("work1_kabupaten_name", StringType(), True),
                    StructField("work1_province_name", StringType(), True),
                    StructField("distance", DoubleType(), True),
                ]
            ),
        )

        work_agg_df = spark_session.createDataFrame(
            data=[
                [
                    "imsi_1",
                    "2020-03",
                    3386.0,
                    "qqu6d",
                    "kelurahan_3",
                    "neighbor_kelurahan_5",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    2,
                    336.0,
                    1,
                    -6.38925,
                    106.9885,
                    0,
                    "2000-01-22",
                ],
                [
                    "imsi_1",
                    "2020-03",
                    3860.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    3860.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-22",
                ],
                [
                    "imsi_1",
                    "2020-04",
                    3604.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    3604.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-23",
                ],
                [
                    "imsi_1",
                    "2020-05",
                    3360.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    3360.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-24",
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("mo_id", StringType(), False),
                    StructField("work1_duration_max", DoubleType(), True),
                    StructField("geohash", StringType(), False),
                    StructField("work1_kelurahan_name", StringType(), True),
                    StructField("work1_neighboring_kelurahan_name", StringType(), True),
                    StructField("work1_kecamatan_name", StringType(), True),
                    StructField("work1_kabupaten_name", StringType(), True),
                    StructField("work1_province_name", StringType(), True),
                    StructField("work1_days", LongType(), True),
                    StructField("work1_duration", DoubleType(), True),
                    StructField("village_cnt", LongType(), True),
                    StructField("work1_lat", DoubleType(), True),
                    StructField("work1_lon", DoubleType(), True),
                    StructField("duration_max_flag", IntegerType(), False),
                    StructField("month_mapped_dt", StringType(), False),
                ]
            ),
        )

        poi_agg_df = spark_session.createDataFrame(
            data=[
                [
                    "supermarket",
                    106.9882,
                    -6.3892,
                    "commercial",
                    "commercial-store",
                    "qqu57",
                    "qqu59",
                ],
                [
                    "supermarket",
                    106.9882,
                    -6.3892,
                    "commercial",
                    "commercial-store",
                    "qqu57",
                    "qqu5e",
                ],
                [
                    "supermarket",
                    106.9882,
                    -6.3892,
                    "commercial",
                    "commercial-store",
                    "qqu57",
                    "qqu5c",
                ],
                [
                    "supermarket",
                    106.9882,
                    -6.3892,
                    "commercial",
                    "commercial-store",
                    "qqu57",
                    "qqu5f",
                ],
                [
                    "supermarket",
                    106.9882,
                    -6.3892,
                    "commercial",
                    "commercial-store",
                    "qqu57",
                    "qqu5g",
                ],
                [
                    "supermarket",
                    106.9882,
                    -6.3892,
                    "commercial",
                    "commercial-store",
                    "qqu57",
                    "qqu53",
                ],
                [
                    "supermarket",
                    106.9882,
                    -6.3892,
                    "commercial",
                    "commercial-store",
                    "qqu57",
                    "qqu56",
                ],
                [
                    "supermarket",
                    106.9882,
                    -6.3892,
                    "commercial",
                    "commercial-store",
                    "qqu57",
                    "qqu5d",
                ],
                [
                    "mall",
                    106.988,
                    -6.3892,
                    "commercial",
                    "commercial",
                    "qqu5c",
                    "qqu59",
                ],
                [
                    "mall",
                    106.988,
                    -6.3892,
                    "commercial",
                    "commercial",
                    "qqu5c",
                    "qqu5e",
                ],
                [
                    "mall",
                    106.988,
                    -6.3892,
                    "commercial",
                    "commercial",
                    "qqu5d",
                    "qqu5d",
                ],
                [
                    "mall",
                    106.988,
                    -6.3892,
                    "commercial",
                    "commercial",
                    "qqu5c",
                    "qqu5f",
                ],
                [
                    "mall",
                    106.988,
                    -6.3892,
                    "commercial",
                    "commercial",
                    "qqu5c",
                    "qqu5g",
                ],
                [
                    "mall",
                    106.988,
                    -6.3892,
                    "commercial",
                    "commercial",
                    "qqu5c",
                    "qqu53",
                ],
                [
                    "mall",
                    106.988,
                    -6.3892,
                    "commercial",
                    "commercial",
                    "qqu5c",
                    "qqu56",
                ],
                [
                    "mall",
                    106.988,
                    -6.3892,
                    "commercial",
                    "commercial",
                    "qqu5c",
                    "qqu57",
                ],
            ],
            schema=StructType(
                [
                    StructField("category", StringType(), False),
                    StructField("longitude", DoubleType(), True),
                    StructField("latitude", DoubleType(), True),
                    StructField("category_type_1", StringType(), True),
                    StructField("category_type_2", StringType(), True),
                    StructField("poi_geohash", StringType(), False),
                    StructField("poi_neighbor_geohash", StringType(), True),
                ]
            ),
        )

        actual_fea_df = mobility_work_poi_features(work_agg_df, poi_agg_df)

        expected_fea_df = spark_session.createDataFrame(
            data=[
                ["imsi_1", "2020-03", 750.586091493751, 1, 1150.86091493751, 0,],
                ["imsi_1", "2020-04", 750.586091493751, 1, 1150.86091493751, 0,],
                ["imsi_1", "2020-05", 750.586091493751, 1, 1150.86091493751, 0,],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("mo_id", StringType(), False),
                    StructField(
                        "fea_mobility_work_cat_1_commercial_min_poi_dist",
                        DoubleType(),
                        True,
                    ),
                    StructField(
                        "fea_mobility_work_cat_1_commercial_poi_1km_num",
                        LongType(),
                        True,
                    ),
                    StructField(
                        "fea_mobility_work_cat_2_commercial_min_poi_dist",
                        DoubleType(),
                        True,
                    ),
                    StructField(
                        "fea_mobility_work_cat_2_commercial_poi_1km_num",
                        LongType(),
                        True,
                    ),
                ]
            ),
        )

        assert_df_frame_equal(actual_fea_df, expected_fea_df)
