from pyspark.sql import SparkSession
from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
)

from src.dmp.pipelines.dmp._04_features.mobility.nodes.fea_home_stay_freq import (
    mobility_home_stay_freq_features,
)
from src.tests.pysaprk_df_equality import assert_df_frame_equal


class TestFeaHomeStayFreq:
    def test_fea_home_stay_freq(self, spark_session: SparkSession):
        home_agg_df = spark_session.createDataFrame(
            data=[
                [
                    "imsi_1",
                    "2020-01",
                    33860.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-20",
                ],
                [
                    "imsi_1",
                    "2020-02",
                    33860.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-21",
                ],
                [
                    "imsi_1",
                    "2020-03",
                    33860.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-22",
                ],
                [
                    "imsi_1",
                    "2020-04",
                    33860.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-23",
                ],
                [
                    "imsi_1",
                    "2020-05",
                    33860.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-25",
                ],
                [
                    "imsi_1",
                    "2020-06",
                    33860.0,
                    "qqu5d",
                    "kelurahan_1",
                    "neighbor_kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    24,
                    33860.0,
                    1,
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-26",
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("mo_id", StringType(), False),
                    StructField("home1_duration_max", DoubleType(), True),
                    StructField("geohash", StringType(), False),
                    StructField("home1_kelurahan_name", StringType(), True),
                    StructField("home1_neighboring_kelurahan_name", StringType(), True),
                    StructField("home1_kecamatan_name", StringType(), True),
                    StructField("home1_kabupaten_name", StringType(), True),
                    StructField("home1_province_name", StringType(), True),
                    StructField("home1_days", LongType(), True),
                    StructField("home1_duration", DoubleType(), True),
                    StructField("village_cnt", LongType(), True),
                    StructField("home1_lat", DoubleType(), True),
                    StructField("home1_lon", DoubleType(), True),
                    StructField("duration_max_flag", IntegerType(), False),
                    StructField("month_mapped_dt", StringType(), False),
                ]
            ),
        )

        actual_fea_df = mobility_home_stay_freq_features(home_agg_df)

        expected_fea_df = spark_session.createDataFrame(
            data=[
                [
                    "imsi_1",
                    "2020-01",
                    1,
                    "kelurahan_1",
                    1,
                    "kelurahan_1",
                    1,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    1,
                    "kecamatan_3",
                    1,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    1,
                    "kabu_4",
                    1,
                    "kabu_4",
                    1,
                    "provinc_6",
                    1,
                    "provinc_6",
                    1,
                    "provinc_6",
                ],
                [
                    "imsi_1",
                    "2020-02",
                    1,
                    "kelurahan_1",
                    2,
                    "kelurahan_1",
                    2,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    2,
                    "kecamatan_3",
                    2,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    2,
                    "kabu_4",
                    2,
                    "kabu_4",
                    1,
                    "provinc_6",
                    2,
                    "provinc_6",
                    2,
                    "provinc_6",
                ],
                [
                    "imsi_1",
                    "2020-03",
                    1,
                    "kelurahan_1",
                    3,
                    "kelurahan_1",
                    3,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    3,
                    "kecamatan_3",
                    3,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    3,
                    "kabu_4",
                    3,
                    "kabu_4",
                    1,
                    "provinc_6",
                    3,
                    "provinc_6",
                    3,
                    "provinc_6",
                ],
                [
                    "imsi_1",
                    "2020-04",
                    1,
                    "kelurahan_1",
                    3,
                    "kelurahan_1",
                    4,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    3,
                    "kecamatan_3",
                    4,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    3,
                    "kabu_4",
                    4,
                    "kabu_4",
                    1,
                    "provinc_6",
                    3,
                    "provinc_6",
                    4,
                    "provinc_6",
                ],
                [
                    "imsi_1",
                    "2020-05",
                    1,
                    "kelurahan_1",
                    2,
                    "kelurahan_1",
                    5,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    2,
                    "kecamatan_3",
                    5,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    2,
                    "kabu_4",
                    5,
                    "kabu_4",
                    1,
                    "provinc_6",
                    2,
                    "provinc_6",
                    5,
                    "provinc_6",
                ],
                [
                    "imsi_1",
                    "2020-06",
                    1,
                    "kelurahan_1",
                    2,
                    "kelurahan_1",
                    5,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    2,
                    "kecamatan_3",
                    5,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    2,
                    "kabu_4",
                    5,
                    "kabu_4",
                    1,
                    "provinc_6",
                    2,
                    "provinc_6",
                    5,
                    "provinc_6",
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("mo_id", StringType(), False),
                    StructField(
                        "fea_mobility_home_kelurahan_cnt_01m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kelurahan_name_01m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kelurahan_cnt_03m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kelurahan_name_03m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kelurahan_cnt_06m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kelurahan_name_06m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kecamatan_cnt_01m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kecamatan_name_01m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kecamatan_cnt_03m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kecamatan_name_03m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kecamatan_cnt_06m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kecamatan_name_06m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kabupaten_cnt_01m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kabupaten_name_01m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kabupaten_cnt_03m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kabupaten_name_03m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kabupaten_cnt_06m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_kabupaten_name_06m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_province_cnt_01m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_province_name_01m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_province_cnt_03m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_province_name_03m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_province_cnt_06m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_home_province_name_06m", StringType(), True,
                    ),
                ]
            ),
        )

        assert_df_frame_equal(actual_fea_df, expected_fea_df)
