from pyspark.sql import SparkSession
from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
)

from src.dmp.pipelines.dmp._04_features.mobility.nodes.fea_staypoint_freq import (
    mobility_staypoint_freq_features,
)
from src.tests.pysaprk_df_equality import assert_df_frame_equal


class TestFeaStaypointFreq:
    def test_fea_staypoint_freq(self, spark_session: SparkSession):
        staypoint_df = spark_session.createDataFrame(
            data=[
                [
                    "imsi_1",
                    "2020-01",
                    "qqu5d",
                    7200,
                    "kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-20",
                    7200,
                    1,
                ],
                [
                    "imsi_1",
                    "2020-02",
                    "qqu5d",
                    14880,
                    "kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-21",
                    14880,
                    1,
                ],
                [
                    "imsi_1",
                    "2020-03",
                    "qqu5d",
                    7200,
                    "kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-22",
                    7200,
                    1,
                ],
                [
                    "imsi_1",
                    "2020-04",
                    "qqu5d",
                    11280,
                    "kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-23",
                    11280,
                    1,
                ],
                [
                    "imsi_1",
                    "2020-05",
                    "qqu5d",
                    7200,
                    "kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-24",
                    7200,
                    1,
                ],
                [
                    "imsi_1",
                    "2020-06",
                    "qqu5d",
                    29280,
                    "kelurahan_1",
                    "kecamatan_3",
                    "kabu_4",
                    "provinc_6",
                    -6.38925,
                    106.98825,
                    1,
                    "2000-01-25",
                    29280,
                    1,
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("mo_id", StringType(), False),
                    StructField("geohash", StringType(), False),
                    StructField("agg_duration", LongType(), True),
                    StructField("kelurahan_name", StringType(), True),
                    StructField("kecamatan_name", StringType(), True),
                    StructField("kabupaten_name", StringType(), True),
                    StructField("province_name", StringType(), True),
                    StructField("lat1", DoubleType(), True),
                    StructField("long1", DoubleType(), True),
                    StructField("village_cnt", LongType(), False),
                    StructField("month_mapped_dt", StringType(), False),
                    StructField("agg_duration_max", LongType(), False),
                    StructField("duration_max_flag", IntegerType(), False),
                ]
            ),
        )

        actual_fea_df = mobility_staypoint_freq_features(staypoint_df)

        expected_fea_df = spark_session.createDataFrame(
            data=[
                [
                    "imsi_1",
                    "2020-01",
                    1,
                    "kelurahan_1",
                    1,
                    "kelurahan_1",
                    1,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    1,
                    "kecamatan_3",
                    1,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    1,
                    "kabu_4",
                    1,
                    "kabu_4",
                    1,
                    "provinc_6",
                    1,
                    "provinc_6",
                    1,
                    "provinc_6",
                ],
                [
                    "imsi_1",
                    "2020-02",
                    1,
                    "kelurahan_1",
                    2,
                    "kelurahan_1",
                    2,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    2,
                    "kecamatan_3",
                    2,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    2,
                    "kabu_4",
                    2,
                    "kabu_4",
                    1,
                    "provinc_6",
                    2,
                    "provinc_6",
                    2,
                    "provinc_6",
                ],
                [
                    "imsi_1",
                    "2020-03",
                    1,
                    "kelurahan_1",
                    3,
                    "kelurahan_1",
                    3,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    3,
                    "kecamatan_3",
                    3,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    3,
                    "kabu_4",
                    3,
                    "kabu_4",
                    1,
                    "provinc_6",
                    3,
                    "provinc_6",
                    3,
                    "provinc_6",
                ],
                [
                    "imsi_1",
                    "2020-04",
                    1,
                    "kelurahan_1",
                    3,
                    "kelurahan_1",
                    4,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    3,
                    "kecamatan_3",
                    4,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    3,
                    "kabu_4",
                    4,
                    "kabu_4",
                    1,
                    "provinc_6",
                    3,
                    "provinc_6",
                    4,
                    "provinc_6",
                ],
                [
                    "imsi_1",
                    "2020-05",
                    1,
                    "kelurahan_1",
                    3,
                    "kelurahan_1",
                    5,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    3,
                    "kecamatan_3",
                    5,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    3,
                    "kabu_4",
                    5,
                    "kabu_4",
                    1,
                    "provinc_6",
                    3,
                    "provinc_6",
                    5,
                    "provinc_6",
                ],
                [
                    "imsi_1",
                    "2020-06",
                    1,
                    "kelurahan_1",
                    3,
                    "kelurahan_1",
                    6,
                    "kelurahan_1",
                    1,
                    "kecamatan_3",
                    3,
                    "kecamatan_3",
                    6,
                    "kecamatan_3",
                    1,
                    "kabu_4",
                    3,
                    "kabu_4",
                    6,
                    "kabu_4",
                    1,
                    "provinc_6",
                    3,
                    "provinc_6",
                    6,
                    "provinc_6",
                ],
            ],
            schema=StructType(
                [
                    StructField("msisdn", StringType(), False),
                    StructField("mo_id", StringType(), False),
                    StructField(
                        "fea_mobility_staypoint_kelurahan_cnt_01m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kelurahan_name_01m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kelurahan_cnt_03m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kelurahan_name_03m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kelurahan_cnt_06m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kelurahan_name_06m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kecamatan_cnt_01m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kecamatan_name_01m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kecamatan_cnt_03m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kecamatan_name_03m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kecamatan_cnt_06m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kecamatan_name_06m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kabupaten_cnt_01m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kabupaten_name_01m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kabupaten_cnt_03m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kabupaten_name_03m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kabupaten_cnt_06m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_kabupaten_name_06m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_province_cnt_01m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_province_name_01m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_province_cnt_03m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_province_name_03m", StringType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_province_cnt_06m", LongType(), True,
                    ),
                    StructField(
                        "fea_mobility_staypoint_province_name_06m", StringType(), True,
                    ),
                ]
            ),
        )

        assert_df_frame_equal(actual_fea_df, expected_fea_df)
